### ISSUE TITLE
Diskussion in Gruppe, layer übereinander

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#100]
![gruppendiskussion](https://cloud.githubusercontent.com/assets/1484773/21976595/eae62a90-dbd2-11e6-957a-c1f713072ca6.png)

**Comment by loughin** [comment]
Schließlich gelang es mir, den Fehler mit ein paar CSS-Befehlen zu beheben,

**Comment by kleinfe** [comment]
super, passt!
