### ISSUE TITLE
Projektkatalog sollte an neues design und css angepasst werden

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#101]

**Comment by loughin** [comment]
projekt Catalog ist ein externer Link. Die CSS der Seite können nicht vom Server geändert werden. Die einzige Lösung ist es, die Seite im Server zu speichern. Ich weiß aber nicht, wo ich die Informationen des katalogs finden kann.

**Comment by vmakarenko** [comment]
For the  would be enogh to have same design as for login page, i.e. same footer, header and css

**Comment by vmakarenko** [comment]
This design should be integrated in the catalog template: https://github.com/MPDL/KEEPER/blob/master/seafile_keeper_ext/seafile-server-latest/seahub/keeper/catalog/main.tpl

**Comment by vmakarenko** [comment]
Wrong implementation of footer in 
https://github.com/MPDL/KEEPER/blob/master/seafile_keeper_ext/seafile-server-latest/seahub/keeper/catalog/main.tpl
![keeper4](https://cloud.githubusercontent.com/assets/4024310/23126240/1ade4e6c-f776-11e6-90d5-ac48602a756d.png)

**Comment by kleinfe** [comment]
checked
