### ISSUE TITLE
Startseite IE - MPDL Logo gigantisch groß

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#102]
![startseite ie](https://cloud.githubusercontent.com/assets/1484773/21977277/c3b993e6-dbd5-11e6-9935-f8b9375f2bbc.png)

**Comment by kleinfe** [comment]
still not working on my IE
(If you need windows and IE to test let me know!)

**Comment by vmakarenko** [comment]
New issue: bad scaling of the huge file (237KB) in IE 11
![keeper1](https://cloud.githubusercontent.com/assets/4024310/22974748/14ab9bf8-f384-11e6-9f53-90237655b7d9.png)
Pls, scale it in a picture editor to an applicable size

**Comment by kleinfe** [comment]
checked
