### ISSUE TITLE
File Grid Ansicht - Kontextmenü fehlt

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#105]
Im Vergleich zur Seafile Demo:
![contextmenu](https://cloud.githubusercontent.com/assets/1484773/21978015/013b422a-dbd9-11e6-8e5a-163194653560.png)

**Comment by loughin** [comment]
![bildschirmfoto vom 2017-01-16 17-14-41](https://cloud.githubusercontent.com/assets/23240192/21990537/7c1712ae-dc0f-11e6-9692-261f94467d60.png)

**Comment by loughin** [comment]
Hier ist ein Kommentar, das ich im Forum gefunden habe. Ich habe auch bei mir versucht, auf die vorige Version von Seafile (nämlich 6.0.5 oder sogar 6.0.3) zurückzukommen und der Kontext-Menü wird angezeigt...
