### ISSUE TITLE
Falsches Pop-Up-Fenster bei erster Anmeldung 

### ISSUE THREAD

**Issue by loughin** [MPDL/KEEPER#107]
![bildschirmfoto vom 2017-01-16 14-25-56](https://cloud.githubusercontent.com/assets/23240192/21985533/7086c754-dbfb-11e6-954b-f2c6b5740672.png)

**Comment by loughin** [comment]
![bildschirmfoto vom 2017-01-16 15-15-04](https://cloud.githubusercontent.com/assets/23240192/21986165/ab87b0d6-dbfe-11e6-9204-ea955abde67f.png)

bitte Bescheid sagen, wenn der Text anzupassen ist

**Comment by kleinfe** [comment]
checked
