### ISSUE TITLE
Seafile Logo within the tab title

### ISSUE THREAD

**Issue by loughin** [MPDL/KEEPER#108]
![bildschirmfoto vom 2017-01-16 15-21-40](https://cloud.githubusercontent.com/assets/23240192/21986381/7f5d8958-dbff-11e6-87c8-c1f24012b7b2.png)

**Comment by loughin** [comment]
![bildschirmfoto vom 2017-01-16 16-02-33](https://cloud.githubusercontent.com/assets/23240192/21987812/3aa8090e-dc05-11e6-8675-818161cc0b99.png)

**Comment by kleinfe** [comment]
checked
