### ISSUE TITLE
Footer is disabled for https://dev-keeper.mpdl.mpg.de/home/wiki/

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#109]

**Comment by loughin** [comment]
Das Problem liegt nicht an meiner css Datei; Ich glaube die haben absichtlich den Footer in diesem Bereich der Website vernachlässigt.

**Comment by kleinfe** [comment]
@vmakarenko Pls. report to seafile if this is a bug we need to have fixed.
I close it as there is nothing more to do from our side.

**Comment by vmakarenko** [comment]
Related ticket https://github.com/haiwen/seahub/issues/1470
