### ISSUE TITLE
To Test: Single File Recovery after checksum failure

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#11]

**Comment by vmakarenko** [comment]
Results: https://keeper.mpdl.mpg.de/f/985ecd80ef/

**Comment by vmakarenko** [comment]
check use case: 
- `seaf-fsck` founds a corrupted block of a file
- no `repair` option is used by `seaf-fsck` 
- corrupted block is restored from TSM and added to file storage

**Comment by vmakarenko** [comment]
See https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20System%20Administration/integrity-checking.md, 
find item: "Restore the block from keeper backup"

**Comment by kleinfe** [comment]
done

**Comment by vmakarenko** [comment]
New workflow is decribed in https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20System%20Administration/Backup&Recovery.md 
## Recovery of damaged blocks manually
