### ISSUE TITLE
Update archive-metadata.md on live server

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#110]
With new release in 'My Library Template'

**Comment by vmakarenko** [comment]
There are 2 places for the template: 
Login as Admin: 
System-Administration/System/My Library Template/archive-metadata.md
and Meine Bibliotheken / Keeper Default Library/archive-metadata.md
This should be consolidated in only one place, i.e. System-Administration/System/My Library Template/archive-metadata.md

**Comment by kleinfe** [comment]
Still have to update the file, after new release on live server

**Comment by kleinfe** [comment]
done
