### ISSUE TITLE
Bug: Links of footer -> keeper.mpdl.mpg.de

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#120]
Testserver: https://qa-keeper.mpdl.mpg.de
Browser: ff 
Version: Seafile 6.0.7 - test date 170208     
User: hofmann@mpdl.mpg.de

Actions:  start page keeper -> footer menue -> "About Keeper" 
-> "Keeper Logo"

Observation: The first two times I clicked on the logo to get back to start page, I had to log in again. 
but could not reproduce anymore.
-> All the links of the footer are pointing on https://keeper.mpdl.mpg.de, clicking on the keeper Logo to get back to start page, user is redirected to other keeper instance (start page of keeper.mpdl.mpg.de).

Expected Result: User stays on qa-keeper.mpdl-de for all actions.

**Comment by vmakarenko** [comment]
Tip: we should implement instance-related KEEPER logos to avoid the misleading

**Comment by vmakarenko** [comment]
See #54 as well
