### ISSUE TITLE
bug: Project catalog is empty

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#122]
Testserver: https://qa-keeper.mpdl.mpg.de
Browser: ff
Version: Seafile 6.0.7 - test date 170208
User: hofmann@mpdl.mpg.de

Actions: open project catalog
start page -> "Project Catalog"

Observation: Project catalog is empty and the design of the footer is changed to the "old design"

Expected Result: All libraries available in qa-keeper are provided.
![grafik](https://cloud.githubusercontent.com/assets/14921701/22732085/323615a0-eded-11e6-829c-5e13f824c523.png)

**Comment by vmakarenko** [comment]
works again, pls. test again

**Comment by kleinfe** [comment]
It seems to be very inconsistent, sometimes it works sometimes not. Please test carefully from all possible links to project catalog
1. from startpage
2. from footer logged in
3. from footer not logged in

**Comment by kleinfe** [comment]
still the case, please check carefully

**Comment by vmakarenko** [comment]
added new monitoring check in KEEPER icingaweb2,
e.g. https://mpdl-monitoring.mpdl.mpg.de/icingaweb2/monitoring/list/services?host=lta02-mpdl.esc.rzg.mpg.de#!/icingaweb2/monitoring/service/show?host=lta02-mpdl.esc.rzg.mpg.de&service=MPCDF%20Site%20Content%20-%20qa-keeper.mpdl.mpg.de%20catalog

**Comment by hofmannc** [comment]
Testserver: https://qa-keeper.mpdl.mpg.de
Browser: ff
Version: Seafile 6.0.7 - test date 170308
User: hofmann@mpdl.mpg.de

Result: ok, checked all accesses
