### ISSUE TITLE
Enhancement: revise icons for password protection/locked metadata form

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#126]
Testserver: https://qa-keeper.mpdl.mpg.de
Browser: ff
Version: Seafile 6.0.7 - test date 170208
User: hofmann@mpdl.mpg.de

Actions: create pasword protected library and lock metadata profile

Observation:  similar icons for two actions:
the symbol for a password protected library is a lock 
![grafik](https://cloud.githubusercontent.com/assets/14921701/22734759/24699410-edf7-11e6-9a04-0ae8804b2df3.png)

the menue icon for locking a metadata form is a lock, too: 
![grafik](https://cloud.githubusercontent.com/assets/14921701/22734809/4e7831d0-edf7-11e6-8301-8cc407b5655b.png)

and the symbol for a locked metadata form is 
![grafik](https://cloud.githubusercontent.com/assets/14921701/22734849/73a90c68-edf7-11e6-93da-1d081e60af2e.png)

Expected Result: At first I thought, the password protected library is a locked library.

**Comment by vmakarenko** [comment]
Enhancement, UX: probably an issue for seafile. TBD
