### ISSUE TITLE
Bug/Enhancement: restore invalid metadata form

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#127]
Testserver: https://qa-keeper.mpdl.mpg.de
Browser: ff
Version: Seafile 6.0.7 - test date 170208
User: hofmann@mpdl.mpg.de

Actions: restore metadata form
Start page -> "My libraries" -> "[library]" -> "archive-metadata.md" -> "History"

Observation: If I click on "restore" of an invalid version of the metadata form, User gets system information "Restore successful". But the certificate is actually not updated (which ist the correct behaviour, right?).

Expected Result: Info, that restore was not successful.

**Comment by kleinfe** [comment]
This behavior is right, as the restore only refers to the restore of the metadata.md file and not the certificate. I agree that this is not the best behavior and it will be fixed with an overall rework of the certificate functionality
