### ISSUE TITLE
Enhancement: Double confirmation for "share" 

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#128]
Testserver: https://qa-keeper.mpdl.mpg.de
Browser: ff
Version: Seafile 6.0.7 - test date 170208
User: hofmann@mpdl.mpg.de

Actions: share file
Start page -> "My libraries" -> "[library]" -> "archive-metadata.md" ->"share"

Observation:  Right now, the user just clicks on "share" and the item is published. 

Proposal: From data protection point of view it would make sense to inform user explicitely about the fact that his files are public after the current action and let him confirm this: e.g. "Share" -> "with this action, the file will be accessible for public, are you sure?" -> "ok"

**Comment by vmakarenko** [comment]
Enhancement: nice to have, probably should be explained to user what sharing means, easiest way: popup title by mouseover

**Comment by kleinfe** [comment]
This is a core functionality of seafile and can not be changed by us. I will forward this issue
