### ISSUE TITLE
Farbanpassungen

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#129]
Bitte Screenshots checken und orangen farben austauschen
![context menu_mylibraries](https://cloud.githubusercontent.com/assets/1484773/22929207/ad593196-f2ba-11e6-82bd-c5de0caf8903.png)

![share](https://cloud.githubusercontent.com/assets/1484773/22929217/bfa5cf1c-f2ba-11e6-9096-e9477fcf9962.png)

**Comment by vmakarenko** [comment]
![keeper5](https://cloud.githubusercontent.com/assets/4024310/23222691/0063cdd2-f929-11e6-9a66-5da42fe37203.png)

**Comment by kleinfe** [comment]
Problem of screenshot 1 and 3 are still on qa server. Pls. check if this is a css or deployment problem

**Comment by loughin** [comment]
It is a deployment problem. qa server is not up to date yet. Both commits I did yesterday adress this problem

**Comment by vmakarenko** [comment]
history->details
![keeper6](https://cloud.githubusercontent.com/assets/4024310/23461883/ff604f42-fe8b-11e6-9f30-d339ca9acfe9.png)
