### ISSUE TITLE
CDC - Pls exchange logo in email attachement

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#13]
Looks like an old version. Please use:
https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20Spezifikationen/Cared%20Data%20Certificate/CDC-Images/Keeper-Cared-Data-Certificate-Logo.png

**Comment by vmakarenko** [comment]
It was cropped at the bottom: I've fixed & uploaded

**Comment by kleinfe** [comment]
Checked!
