### ISSUE TITLE
Login Page changes

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#136]
1. Put button "Project Catalog" right after text "Browse all research projects KEEPER"
2. The footer should slide down by overflow of the "Anmeleden" box
3. change 2016 to 2017 in footer
4. the MPDL logo should be smaller, i.e. 105x30px  like on the  https://keeper.mpdl.mpg.de/
5. the link "Download the Keeper client for Windows, Linux and Mac" should point to the "/download_client_program/"

**Comment by vmakarenko** [comment]
![keeper3](https://cloud.githubusercontent.com/assets/4024310/23125562/a57384a6-f772-11e6-8b89-5bc506121f9a.png)

**Comment by kleinfe** [comment]
checked
