### ISSUE TITLE
OPen MPDL ToS -> Can't be found

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#145]
Testserver: keeper
Browser: ff 
Version: ohne Datum 170308        
User: standard user

Actions: open MPDL ToS
start page keeper -> "Project catalog" -> Terms of Services" -> "here"

https://www.mpdl.mpg.de/en/services/tos.html

![grafik](https://cloud.githubusercontent.com/assets/14921701/23695898/aa25f47c-03e1-11e7-9b1c-5074fbdf419a.png)

**Comment by kleinfe** [comment]
Correct link is: https://www.mpdl.mpg.de/en/services/tos 
Please update

**Comment by kleinfe** [comment]
done

**Comment by kleinfe** [comment]
checked
