### ISSUE TITLE
No e-mail with creation of certificate

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#147]
Testserver: qa keeper
Browser: ff chr
Version: ohne Datum 170309       
User: standard user

Actions: create certificate
-> no e-mail is sent out after the creation

Expected result: e-mail sent out, e.g. like:

Von: MPDL Keeper 
Gesendet: Mittwoch, 8. März 2017 09:48
An: Catherina Hofmann; MPDL Keeper
Betreff: Cared Data Certificate for project "170308_lib"

Dear hofmann@mpdl.mpg.de, 
you have successfully registered your research project "der erste titel des tages" by Meier, Hans for long term compliant archiving according to the rules for data storage of the Max Planck Society. The data are kept in the KEEPER system under the library name 170308_lib. 
Maintainer of the Record is hofmann@mpdl.mpg.de. 
Please make sure you use KEEPER in accordance to the KEEPER Terms of Service and the KEEPER Cared Data Commitment. A Cared Data Certificate was automatically added to your project in KEEPER: Cared Data Certificate No. 6 
With best wishes for great progress and break through research results! 
Your
KEEPER Service Team
at the Max Planck Digital Library 
KEEPER Support: keeper@mpdl.mpg.de
KEEPER Service Site: https://qa-keeper.mpdl.mpg.de
a service of the
Max Planck Digital Library (MPDL), Amalienstr. 33, D-80799 München, Germany, www.mpdl.mpg.de, 
Hotline +49 (0) 89 38602-243 (Montag bis Freitag 7:00-19:00)
Max-Planck-Gesellschaft zur Förderung der Wissenschaften e.V.

**Comment by kleinfe** [comment]
checked
