### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#151]
As the catalog is not yet internationalized the wording should be in english
Projektarchiv Nr. 123 => Project archive no.123

**Comment by vmakarenko** [comment]
We need an internationalization concept for catalog (design, text, etc.)

**Comment by kleinfe** [comment]
You are right, but I would reschedule this for a later release. For now we provide the catalog only in english I would say.

**Comment by kleinfe** [comment]
done
