### ISSUE TITLE
Design of catalog enhancement

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#154]
![catalogv2](https://cloud.githubusercontent.com/assets/1484773/23945171/c733cf28-0975-11e7-9ca2-d9f843c9e1b5.png)

**Comment by vmakarenko** [comment]
Comments:
-  **List of the institutions**: how it should be handled? If we get it from the Institute field of the  archive-metadata.md, we will not be able to avoid duplicates, typos, etc. Thus the list will be long and inconsistent. Solution: managed list of institutions/affiliations. TBD
-  **Search field**: where it should be searched, how the a search result list should be presented? Probably, the better solution would be some filter which includes the catalog entries with the fields matched the filter.
