### ISSUE TITLE
Small layout/typo changes

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#157]
Testserver: qa keeper
Browser: ff chr
Version: Seafile 6.0.7 ohne Datum 170322
User: not logged in

Observation 1: -> open impressum
please see Zeilenumbruch in third line of first block and ".." in forth line of second block
![grafik](https://cloud.githubusercontent.com/assets/14921701/24189949/419c4526-0ee7-11e7-9ce6-a7d537a0f84f.png)

Observation 2: Log in -> "forgot password"
-> "e-mail"
![grafik](https://cloud.githubusercontent.com/assets/14921701/24190041/99ff6dc4-0ee7-11e7-9b6d-b5d209af1dfe.png)

Observation 3: coming from CDC how to -> buttons are not displayed completely
lits of library items -> "Cared Data Certificate How to" -> " https://keeper.mpdl.mpg.de/f/1b0bfceac2/. " ->
![grafik](https://cloud.githubusercontent.com/assets/14921701/24190980/8ba29b54-0eea-11e7-95e5-7874bea2953d.png)

**Comment by vmakarenko** [comment]
1. observation: should be fixed directly in doc file
2. observation: not clear, what is wrong? :)
3. observation: this is the seafile bug:  the clicking the document embedded link leads to the loading of the target into the document viewer iframe. Workaround: press Shift by clicking. Probably we need to inform the seafile regarding the issue.

**Comment by hofmannc** [comment]
regarding 2nd observation: "email" should be changed to "e-mail" ("email" is the english word for "Emaille")

**Comment by vmakarenko** [comment]
2nd: 
* email can be used: https://english.stackexchange.com/questions/1925/email-or-e-mail
* we have to change a lot of seafile source code, `email` is used everywhere

**Comment by kleinfe** [comment]
@hofmannc Pls. check if fixed

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: ff 
Version: Seafile 6.1.3 ohne Datum 170720
User: not logged in

results: 
1. still one line break left:

![grafik](https://user-images.githubusercontent.com/14921701/28404154-76d537da-6d28-11e7-93df-3538fa43efdd.png)
2.ok, you are right, sorry

**Comment by kleinfe** [comment]
fixed

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: ff
test date: 04.09.2017       

Actions: line break still visible
