### ISSUE TITLE
Enhancement: make explicit that user has not grants

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#159]
Current situation:
If a user enters a link for a metadata form which has been "unshared" e.g. https://qa-keeper.mpdl.mpg.de/f/6379c1cdf3/
user gets this info:

![grafik](https://cloud.githubusercontent.com/assets/14921701/24192100/2cf6b668-0eee-11e7-9370-a9f936b9854d.png)

Expected result: user get info that he has no grants and maybe where to receive further info (or just make footer visible for further info on contact)

**Comment by vmakarenko** [comment]
To be specified, can be implemented

**Comment by kleinfe** [comment]
This is a seafile issue, I will forward it to the seafile forum.
