### ISSUE TITLE
History of Certificate deleted with deletion of file

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#160]
Testserver: qa keeper
Browser: ff
Version: Seafile 6.0.7 ohne Datum 170322
User: logged in standard user

Action: view history of certificate

-> delete certificate which has been changed several times earlier -> make change in MD form -> new certificate is created -> view history -> history deleted with the deletion of the certificate, no possibility to restore former version

Expected result: user is able to see (and restore) the complete history from the beginning of the project -> history of the certificate includes also deletion and time before deletion

-> intended behaviour or bug?

**Comment by vmakarenko** [comment]
This is seafile intended behavior: if file/directory has been deleted, the complete history is deleted as well. File can be recovered from trash can, but not the history.
