### ISSUE TITLE
Items of trash are not deleted

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#163]
Testserver: qa keeper
Browser: ff
Version: Seafile 6.0.7 ohne Datum 170323
User: standard user

Action: clean trash
upload files to library -> delete files -> "trash" of library -> "clean" -> 3days ago" -> "submit"

Observation: items stay in list of trash

Expected result: items are finally deleted from library. 
I am pretty sure this worked out yesterday. But yesterday I thought a few times, that the deleted items are not added to trash list but I couldn't reproduce it later - maybe this is the same occurrence. If this is really an issue, this is anyway a Seafile issue, right?

**Comment by kleinfe** [comment]
"clean" -> 3days ago" -> "submit" means all items which were deleted 3 days ago or later will be deleted, if your file is 'younger' it will stay.
Delet - 'All' should bring the right result.

**Comment by hofmannc** [comment]
Thank you :-) so I close this ticket
