### ISSUE TITLE
history - view certificate/metadata form: no link in breadcrumb

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#164]
Testserver: qa keeper
Browser: ff
Version: Seafile 6.0.7 ohne Datum 170323
User: standard user

Action: view former version of certificate / metadata form

certificate -> "Histroy" -> select former version -> "View" ->
![grafik](https://cloud.githubusercontent.com/assets/14921701/24240806/304e795c-0fb3-11e7-9e48-93798b30a24a.png)

Observation: user cannot get back like it is possible e.g. in metadata view

same observation for view metadata form.

![grafik](https://cloud.githubusercontent.com/assets/14921701/24240893/6f3409e8-0fb3-11e7-9988-a6e70af1d138.png)

Expected result: User can use breadcrumb to go back to main views

**Comment by kleinfe** [comment]
This is a seafile issue, I will forward it to the seafile forum
