### ISSUE TITLE
Define process for corrupted files

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#166]

**Comment by vmakarenko** [comment]
There are already written manuals, pls. check https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20System%20Administration/Backup%26Recovery.md, chapter 
**Recovery of damaged blocks manually**

**Comment by kleinfe** [comment]
done
