### ISSUE TITLE
check mmbackup status

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#168]
Possibly markers for failed mmbackup:
**Location:** lta03-mpdl.esc.rzg.mpg.de:/var/log/mmbackup/keeper_backup.[DATE].log
**Failure patterns:**
- "TSM exit status:  exit 12"
- "Its shadow database has not been updated. Shadow DB state:unknown"
-  "mmbackup:Incremental backup completely failed."

**Success patterns**:
- "mmbackup:Completed backup and expire jobs"
- "Its shadow database has been updated. Shadow DB state:updated"
- "Total number of bytes transferred:  `NUMBER_IN_BYTES`", `NUMBER_IN_BYTES` > 0

**Comment by kleinfe** [comment]
Pls update this issue, is there anything to do?

**Comment by vmakarenko** [comment]
Please, create icinga check for keeper backup with control string:
"mmbackup: Command failed"

**Comment by kleinfe** [comment]
@mpdl-knoth any update?

**Comment by kleinfe** [comment]
pls. update this issue
