### ISSUE TITLE
test GPFS recovery from snapshot feature

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#169]
https://www.ibm.com/support/knowledgecenter/SSFKCN_4.1.0/com.ibm.cluster.gpfs.v4r1.gpfs200.doc/bl1adv_restrfs.htm
Rational: recovery with `cp/rsync` from a GPS snapshot is not acceptable (too long), try GPFS `mmrestorefs` feature

**Comment by kleinfe** [comment]
To be discussed with MPCDF
