### ISSUE TITLE
consolidate keeper logs

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#170]
Related: KEEPER log list: [Logging.md](https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20System%20Administration/Logging.md)
#180

**Comment by kleinfe** [comment]
Please update documentation as discussed in last meeting:
- Grobe Beschreibung was steht in den Logfiles
- Wieviele Versionen des Logfiles werden aufgehoben
- Welche Informationen werden aus den Logfiles für das Monitoring gezogen.

Sobald die Bestandsaufnahme beendet ist bitte neues Meeting (Vlad, Benjamin, Rike) ansetzen

**Comment by vmakarenko** [comment]
TBD: add syslog integration https://manual.seafile.com/deploy/using_syslog.html

**Comment by vmakarenko** [comment]
Bestandsaufnahme ist durchgeführt und protokoliert in  [Logging.md](https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20System%20Administration/Logging.md)

**Comment by vmakarenko** [comment]
Fazit: kibana is preferable as syslog for log analyze and visualization, see #181

**Comment by kleinfe** [comment]
@vmakarenko Bitte neues Meeting ansetzen um das thema abschließen zu können, bzw. den aktuellen status festzulegen

**Comment by kleinfe** [comment]
change to epic
