### ISSUE TITLE
Check out how to restore single corrupted file

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#174]
and test on qa server

**Comment by vmakarenko** [comment]
See https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20System%20Administration/Backup%26Recovery.md
Chapter **Recovery of damaged blocks manually**

**Comment by kleinfe** [comment]
Pls. go through this with benjamin, so he can do it as well and to make sure procedure is complete

**Comment by kleinfe** [comment]
done
