### ISSUE TITLE
Login not possible at webpage on mobile browsers

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#177]

**Comment by vmakarenko** [comment]
Login is possible for Android chrome 57.0.2987.132

**Comment by kleinfe** [comment]
checked, works fine

**Comment by hofmannc** [comment]
log in possible for android chrome 60.0.3112.107

**Comment by hofmannc** [comment]
log in possible for android chrome 60.0.3112.107
but could not find footer in start page
