### ISSUE TITLE
Evaluate sharepoint integration in Keeper

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#178]
Pls. check if and how it would be possible to sync Keeper data with an existing sharepoint instance.

**Comment by kleinfe** [comment]
Pls check this issue as i need the outcome for a meeting at June 19th

**Comment by vmakarenko** [comment]
There is no seafile / SharePoint integration, there is no even feature request for this (https://forum.seafile.com/c/feature). Suggested solutions for collaborative editing of shared documents are:
- interation with Microsoft Office Online Server (see https://manual.seafile.com/deploy_pro/office_web_app.html)
- integration with Collabora Online (LibreOffice Online) (see https://manual.seafile.com/deploy/libreoffice_online.html)
Another interesting option is an [OnlyOffice](https://www.onlyoffice.com/) integration (see https://manual.seafile.com/deploy/only_office.html), OnlyOffice is more compatible with MS Documents and more stable as Collabora (curren status, Collabora is constantly improved)
At this moment keeper uses  read-only documents rendering with the Libreoffice/UNO ()

**Comment by kleinfe** [comment]
Vielleicht über WebDav?

**Comment by kleinfe** [comment]
Zu klären integration auf welcher Ebene? Synchronisieren sich die Sever oder wird mit verscheidenen Clients gearbeitet.

**Comment by kleinfe** [comment]
@vmakarenko : Auf der Cs3 gab es wohl einen vortrag der darum ging ein Protokoll für den Datenaustausch verschiedener Sync&Share Anwendungen zu definieren. Kannst du dich bitte darüber informieren, vielleicht eine Idee für eine Sharepoint Anbindung?

**Comment by vmakarenko** [comment]
PREZI: https://indico.cern.ch/event/565381/contributions/2401966/attachments/1405101/2146341/ocm.pdf
Host: https://github.com/GEANT/OCM-API
Last commit: Jan 26, 2017 (no further development)

**Comment by kleinfe** [comment]
Done:     https://keeper.mpdl.mpg.de/f/88e05b3ce77b41e0aa38/
