### ISSUE TITLE
Calculate the costs of 1TB of storage in Keeper

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#179]
of 1 TB of user data, taking into account the backup, the duplication and the tape storage.

**Comment by vmakarenko** [comment]
Without tape strorage estimations:  https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20Konzepte/20170314%20Keeper%20BAR-Antrag/Keeper_1TB_Kosten.xlsx

**Comment by kleinfe** [comment]
Pls update as discussed

**Comment by vmakarenko** [comment]
updated

**Comment by kleinfe** [comment]
Done
