### ISSUE TITLE
Evaluate Kibana for Keeper

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#181]
First Step would be to organize a short workshop for all interested persons in MPDL (would suggest all developers + Anelia).

**Comment by vmakarenko** [comment]
Testing instance: https://dev-keeper.mpdl.mpg.de/kibana

**Comment by kleinfe** [comment]
Find appointment beginning of July

**Comment by vmakarenko** [comment]
ELK stack is deployed at configured on dev, see https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20System%20Administration/kibana/Kibana.md for comments.

**Comment by vmakarenko** [comment]
Added  [nginx-latcency-howto.md](https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20System%20Administration/kibana/nginx-latcency-howto.md)
Status: ELK is fully deployed on dev-keeper. License for _xpack is valid untill end of July.
