### ISSUE TITLE
Client download for Mac: correct default folder?

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#187]
Testserver: qa keeper
Browser: ff / mac
Test date: 12.07.

Actions: download client for Mac from official homepage.
System asks to drag "Seafile- file" to "Applications- file" -> done
System asks which file to use as default file for download of Keeper content. -> selected the highest level possible
System asks for server -> pasted "https://qa-keeper.mpdl.mpg.de" and log in data
-> go

--> Keeper/Seafile client is not saved at the place I selected earlier, but in the actually downloaded file in "programs" 

expected behaviour: new file available additionally to the seafile-download file in "Programs"

Download for Windows: 
followed the download instructions, and a new file "Meine Bibliothek" is created automatically on the highest hierarchy level. This is what I expected for Mac as well.
![grafik](https://user-images.githubusercontent.com/14921701/28156107-9989a6d4-67b1-11e7-8a51-06ff9d801f06.png)

**Comment by kleinfe** [comment]
minor
