### ISSUE TITLE
Password issues?

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#188]
Testserver: qa keeper
Browser: ff / mac and ff win
Test date: 12.07.

Action: enter saved password

-> start page keeper -> enter valid e-mail adress -> saved password pops up -> "log in" -> message:  invalid user name or password

but I am quite sure that I did not change my password. (-> same happend with my second acount, same happend to Rike this morning)

-> "Forgot Password" and password could be changed successfully

**Comment by vmakarenko** [comment]
Cannot reproduce, probably took place due to bugfixing process (stop/start server) on qa during the testing
