### ISSUE TITLE
Contact MPCDF to extent storage

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#189]

**Comment by kleinfe** [comment]
Best: Should be done before your holiday

**Comment by kleinfe** [comment]
Pls update this issue, was this done?

**Comment by kleinfe** [comment]
Pls contact MPCDF and CC me. Should be done this week (till 11.8.)

**Comment by vmakarenko** [comment]
Status Di 8. Aug 11:00:50 CEST 2017:
```
Filesystem        Size  Used Avail Use% Mounted on
/dev/gpfs_keeper   17T   14T  3,3T  81% /keeper
```
Suggestion: set to 30T
