### ISSUE TITLE
small layout issues

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#193]
Testserver: qa keeper
Browser: ff
Version: Seafile 6.1.3 ohne Datum 170720

*  make consistent: "Signup" on start page and "Sign Up" on Register form

* White typo turns to blue after download, sometimes it stays blue for a short while (mostly until next click) but I cannot exactly reproduce
![grafik](https://user-images.githubusercontent.com/14921701/28403908-43cdb516-6d27-11e7-9de4-2490f6eff102.png)

* chr / ff -> select library -> history -> select entry -> line break in:  "Schnappschuss ansehen"

**Comment by vmakarenko** [comment]
1. fixed
2. cannot reproduce, pls define location
3. this is the small issue, can be can be leaved as it is or <code>td.word-break</code> style can be changed to <code>break-word</code>

**Comment by hofmannc** [comment]
regarding 2.: 
https://keeper.mpdl.mpg.de/f/f62758e53c/
https://keeper.mpdl.mpg.de/f/1b0bfceac2/
https://keeper.mpdl.mpg.de/f/d17ecbb967/

**Comment by vmakarenko** [comment]
regarding 2.:
fixed, changed to white

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: ff 59.0.1 (64-Bit)
Version: Seafile 6.2.13 ohne Datum 180711

Result: ok
