### ISSUE TITLE
"clean" trash: "3days ago" also deletes items deleted a week ago

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#194]
Testserver: qa keeper
Browser: ff
Version: Seafile 6.1.3 ohne Datum 170720

upload item -> select single items -> delete items -> wait for a week -> come back to library -> delete another item ->  trash -> deleted items listed -> "clear files and trash and history: "3days ago" -> "clean" -> all items are deleted

Expected result: only just now deleted item is removed from list since I selected "3days ago". items deleted a week ago stay in trash..

**Comment by kleinfe** [comment]
This behaviour is intended, actually it means "3days agao and older"
