### ISSUE TITLE
Questions on User handling

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#195]
Current situation:

If I delete user, all shared libraries are not available anymore for other users.

user enters shared link in the browser -> message: no data found
Question:  What happens to files/libraries of deleted users?

Current situation:
If user registers and enter first, he gets a welcome message and one default library is created. If user delets his account and re-registerd, he does not get a welcome message and no library is created. But he can use the system according to rules.

Question: Should the system give the welcome message if a user comes back to Keeper?

**Comment by vmakarenko** [comment]
The use case (delete/recreate an account) is rather rare, TBD
