### ISSUE TITLE
Wrong redirect

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#197]
Hallo,

Ich habe mein erste Bug gefunden:
Erst mal auf https://keeper.mpdl.mpg.de/lib/4797cf79-f514-428d-ac75-8aa3e7077989/file/Buffetliste.xlsx klicken.
Dann auf „AktuellerPfag -> Organisatories“ klicken -> Man landet auf der Seite vom Screenshot.
Der Pfad  „Meine Bibliotheken / Organisatorisches“ ist falsch. Es sollte „Gruppen / MPDL / Organisatorisches“ sein.

Viele Grüße,
Bastien.
![screenshot-keeper mpdl mpg de-2017-07-20-11-24-35](https://user-images.githubusercontent.com/1484773/28814308-554cb4de-769d-11e7-9d0f-80a7310d49ed.png)

**Comment by kleinfe** [comment]
@vmakarenko pls. report to seafile and track progress

**Comment by vmakarenko** [comment]
That can be a feature: Group shared libraries are available both in the <code>Shared with groups</code> and in <code>My Libraries</code> lists, but the links to the files in the lists are same: they point to <code>lib</code>, i.e. to  <code>My Libraries</code> list. TBD

**Comment by kleinfe** [comment]
wont fix
