### ISSUE TITLE
Seafile does not inform that user is not allowed to get grants for the library

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#201]
Testserver: qa keeper
Browser: ff 
Version: Seafile 6.1.3 ohne Datum 170720

Actions: release library for non-user

Select library -> Bibltiothek freigeben -> "Freigabe durch Benutzer" -> enter e-mail with no/inactive Keeper account -> "Speichern" ->

Observation:  entry field is cleared with no further explication

Expected result: user gets informed why field is cleared.

**Comment by vmakarenko** [comment]
Seafile UX issue. This behavior is intuitively correct, user cannot input account which is not available in system and not permitted to share the library.
