### ISSUE TITLE
Missing link in Activation e-mail

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#202]
Testserver: qa keeper
Browser: ff
Version: Seafile 6.1.3 ohne Datum 170720

-> "Anmelden" is not clickable

![grafik](https://user-images.githubusercontent.com/14921701/28923275-c38a9c38-785d-11e7-935c-904aec45e1e3.png)

**Comment by vmakarenko** [comment]
Cannot reproduce, used gmail account for sign up, ff is used. 
**Note:** I get always english email.

**Comment by hofmannc** [comment]
this issue seems to be related to the e-mail client - in client there was no problem clicking the link, in web-browser, link is not displayed. 
Anyways this type of e-mail sent by Keeper was the only one who showed this problem. all other links in e-mails (e.g. "a file is shared to you by keeper") were displayed correctly both in client and webbrowser.
