### ISSUE TITLE
MPDL NetDrives migration to Keeper

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#204]
Evaluate following:
- Which share drives do we have
- Data size and number of files on these shares
- How do we handle these share currently (e.g. backup)

**Comment by kleinfe** [comment]
Documentation: https://keeper.mpdl.mpg.de/f/0691ccf0bf/

**Comment by vmakarenko** [comment]
Updated by Ronny: [SeaDrives@MPDL-Concept.docx](https://keeper.mpdl.mpg.de/lib/4d5c4d41-e028-48d6-83d5-a88d232bcc28/file/SeaDrives%40MPDL-Concept.docx)

**Comment by kleinfe** [comment]
Migration how to: https://keeper.mpdl.mpg.de/f/c09ac7cccd9841479d8a/
Currently tested by Digital Labs Team

**Comment by kleinfe** [comment]
outdated
