### ISSUE TITLE
footer documents: some characters not correctly displayed

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#209]
Testserver: qa keeper
Browser: ff
test date: 04.09.2017       

Actions:
start page -> "about keeper" ->  change "Zeichensatz" to ISO 88591 ->
![grafik](https://user-images.githubusercontent.com/14921701/30016313-d917430c-9154-11e7-9cb4-3268c9f80b98.png)

-> Terms of service -> u.a.
![grafik](https://user-images.githubusercontent.com/14921701/30016384-2fdf2402-9155-11e7-90bf-ad8a152bf147.png)

-> Impressum u.a.
![grafik](https://user-images.githubusercontent.com/14921701/30016464-89ea1092-9155-11e7-9990-9cee8437a4d4.png)

"About Keeper" -> to ISO 8859 5

![grafik](https://user-images.githubusercontent.com/14921701/30016350-0575c392-9155-11e7-9d94-f70c17fef82d.png)

Terms of service -> u.a.
![grafik](https://user-images.githubusercontent.com/14921701/30016424-5b48b73e-9155-11e7-859d-88029bb0eaa3.png)

Impressum -> u.a.
![grafik](https://user-images.githubusercontent.com/14921701/30016482-9f0a3e70-9155-11e7-8812-5c039797992e.png)

expected result: all characters correctly displayed

**Comment by kleinfe** [comment]
this is not a bug as it depends on the encoding
