### ISSUE TITLE
Impressum not available in mobile browser

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#210]
Testserver: qa keeper
Browser: ff
test date: 04.09.2017

Actions: log in on mobile browser

Observation: footer is not available , most important: Impressum not available

Expected result: Impressum is mandatory by law, so this should be implemented as soon as possible

**Comment by kleinfe** [comment]
Pls. inform seafile ltd. about this issue

**Comment by vmakarenko** [comment]
Estimate affords to implement it by MPDL

**Comment by vmakarenko** [comment]
Communicated with seafile, accepted for implementaion

**Comment by kleinfe** [comment]
Done for us. Have to check seafile feedback
