### ISSUE TITLE
Angebot von Seafile einholen - Client Anpassungen

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#216]
Bitte Seafile anschreiben um ein Angebot für folgende Anpassungen einzuholen:
Eine Keeper Version aller Clients (android, IOS, windows, Mac, Linux) mit den Änderungen:
- Keeper Logo
- Keeper Server URL Hardcodiert
- Farbanpassungen
- Direkter Login als Einstiegsseite

mit der Garantie das Sie die Clients für uns für die nächsten 3 Jahre updaten.

**Comment by vmakarenko** [comment]
Gesendet.

**Comment by kleinfe** [comment]
Done
