### ISSUE TITLE
Test Snapshot Labels Seafile API

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#218]
Following functions should be provided:
The Seafile API is to be extended to the extent that it is possible to retrieve:
1. All snapshot labels. Each snapshot label is associated with the corresponding snapshot link.
2. All snapshot labels of a user
3. All snapshot labels of a library
4. All snapshot labels which include a specific search term

How it is described in [offer_snapshot_labels.pdf](https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Seafile/Development/Snapshot%20Labels/offer_snapshot_labels.pdf) and [Seafile API / admin](https://manual.seafile.com/develop/web_api_v2.1.html#admin-only-get-snapshots-by-label) and here: [Seafile API / CRUD](https://manual.seafile.com/develop/web_api_v2.1.html#snapshot-label)

**Comment by kleinfe** [comment]
Additionally implement Unit Tests

**Comment by vmakarenko** [comment]
To be done after migration Keeper to seafile 6.2

**Comment by vmakarenko** [comment]
test slack

**Comment by vmakarenko** [comment]
Test mattemost integration

**Comment by vmakarenko** [comment]
test2

**Comment by vmakarenko** [comment]
test3

**Comment by vmakarenko** [comment]
test4

**Comment by vmakarenko** [comment]
1. `/snapshot_labels/` -  Get the snapshot labels of the current user
=>
`/api/v2.1/revision-tags/tag-names/`
```
[
    "test_tag1_0",
    "test_tag2_0",
    "test_tag3_0"
]
```
2.

**Comment by kleinfe** [comment]
Report to Seafile

**Comment by kleinfe** [comment]
Issue is fixed
