### ISSUE TITLE
Evaluate implementation possiblities of metadata form 

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#220]
Current implementation has following caveats: 
* The markdown format for archive-metadata is not user friendly
* Users are not notified if some fields were not filled correctly.

Specifications and suggestions: https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20Konzepte/20161215%20Keeper%20Spezifikationen/Metadata%20Form/Spezifikation%20Metadata%20Form.docx

**Comment by kleinfe** [comment]
Done
