### ISSUE TITLE
Implement messaging for validation and certification of archive metadata form

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#225]
for validation and certification of archive metadata form

**Comment by vmakarenko** [comment]
The messaging is implemented via seafile notification engine. 
Firstly for CDC processing status.

**Comment by vmakarenko** [comment]
What is implemented for CDC processing results:

* Brief view in the current notifications area (upper-right corner, next to the search field) 
![cdcnotification_brief](https://user-images.githubusercontent.com/4024310/46656526-8fac9380-cbae-11e8-9bfb-db495c61bd47.png)
* Detailed view in detailed notification list (`See All Notifications` link, i.e. `/notification/list/` URL)
![cdcnotification_detailed](https://user-images.githubusercontent.com/4024310/46656687-efa33a00-cbae-11e8-96d3-62c029c7bfef.png)
* Following CDC events should be notified: metadata changed, CDC has been created
* Wrong or not filled required metadata should be notified

**Comment by kleinfe** [comment]
works fine for cdc creation and metadata change

**Comment by kleinfe** [comment]
works fine for wrong and not filled metadata

**Comment by hofmannc** [comment]
Testserver: dev keeper
Browser: ff 59.0.1 (64-Bit)
Version: Seafile 6.3.6 ohne Datum 181017
result: ok

**Comment by kleinfe** [comment]
Done
