### ISSUE TITLE
Define Workflow for Sharepoint integration

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#227]
1. SP User creates Site
2. Shares site to keeper user in SP
3. Keeper Admin couples SP site with Keeper bib
4. Keeper Admin shares bib with Keeper user
5. Keeper user can share with more people

**Comment by kleinfe** [comment]
ToDo:
- Create Keeper user - FK
- Get SharePoint user - FK
- gwdg VM (Windows Client oder Server) - VM/BK
- set up adapter - VM
- Test with Hr. Sander - FK

**Comment by hillermpdl** [comment]
VM wird beantragt und erstellt.

**Comment by kleinfe** [comment]
outdated
