### ISSUE TITLE
CDC - Author format is not checked

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#23]
Following was accepted:
![unbenannt](https://cloud.githubusercontent.com/assets/1484773/18944075/90a34d06-8623-11e6-82fd-d04495666de1.png)

Could be a problem for later parsing e.g. for cataloug

**Comment by vmakarenko** [comment]
Please define citation style for the authors/affiliations

**Comment by vmakarenko** [comment]
Fixed, checked pattern:
^\s*\w+,(\s+[\w.]+)+(;\s*\S+\s*)+

**Comment by kleinfe** [comment]
checked!
