### ISSUE TITLE
Setup KEEPER syslog server

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#230]
1. create syslog VM - BK
1. configure seafile  app servers to output into syslog - VM
1. define logrotate rules - VM
1. use syslog for KEEPER monitoring - BK 
1. data privacy issues - BK 

Related: https://manual.seafile.com/deploy/using_syslog.html, KEEPER [cluster_resources](https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20Software/Architektur/Cluster/KEEPER-Cluster_resources.pdf)

**Comment by mpdl-knoth** [comment]
syslog server is ready

**Comment by vmakarenko** [comment]
Settings (2.) are done, check https://keeper.mpdl.mpg.de/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/file/Keeper%20System%20Administration/Logging.md, 
chapter **Syslog integration**

**Comment by kleinfe** [comment]
pls. close if done
