### ISSUE TITLE
bad rendering of docx preview 

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#231]
Document formtat: docx
Field in form: `Email-Adresse`, value: `scip-office@mpdl.mpg.de`
Shown in document preview: `scp-o,ce@mpdl,mpg.de`
![image001](https://user-images.githubusercontent.com/4024310/33025276-d424985e-ce0d-11e7-8417-87a95345380a.jpg)

To be communicated to Seafile, problem by LibreOffice preview rendering

**Comment by kleinfe** [comment]
will be fixed with upgrade 6.2
