### ISSUE TITLE
What is the purpose/meaning of "None"?

### ISSUE THREAD

**Issue by ioverka** [MPDL/KEEPER#232]
![image](https://user-images.githubusercontent.com/8920469/33113726-ec6bc476-cf59-11e7-8662-1a55f9d9296e.png)

**Comment by kleinfe** [comment]
Hier sollte der Nutzername stehen. Tritt das Problem noch auf? Konnte es bei mir nicht reproduzieren.

**Comment by ioverka** [comment]
Nein, ich kann das Problem heute auch nicht mehr reproduzieren

**Comment by ioverka** [comment]
None is back... at least partially:

![image](https://user-images.githubusercontent.com/8920469/36150082-aa58e01e-10c2-11e8-9770-b66c76b402ca.png)
