### ISSUE TITLE
Replace existing file not possible via "upload" link

### ISSUE THREAD

**Issue by ioverka** [MPDL/KEEPER#237]
Server Version: 6.1.3

Here is the usage scenario:
a) publisher needs to push a title list to MPDL on a monthly base
b) MPDL service page needs to link to latest version of this title list, thus the URL should be stable

My idea was to use Keeper for this scenario and handling
a) via an "Upload Link" to the collection (shared with publisher)
b) via the "Download Link" to the file (incl. the "?dl=1" parameter)

Problem:  Via the upload link a copy of the same file is created with each upload, it doesn't seem to be possible to replace the existing file, see:
![image](https://user-images.githubusercontent.com/8920469/35294954-1d4add3a-0078-11e8-838c-651967642f07.png)

This also will create new download link, thus my initial scenario cannot be carried out this way.

Note: There is no need to provide me with a working solution, I mainly wanted to share my findings/experiences with you ;)

**Comment by MPDLRanger** [comment]
Thanks, but this is by design, since a user who uploads doesn't have the rights to change existing files, just to add new files
