### ISSUE TITLE
Upload of files not sucessful

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#238]
Testserver: http://app-keeper.mpdl.mpg.de
Browser: ff and chrome
test date: 31.01.2018          

Actions:
register as user -> create new library -> upload -> select files
Observation1:
chrome: (Anelias first try)
![grafik](https://user-images.githubusercontent.com/14921701/35612405-fb7e416e-0668-11e8-805c-d09639b0f80c.png)

Observation 2: firefox58.0.1.: 
![grafik](https://user-images.githubusercontent.com/14921701/35612434-0f6080a2-0669-11e8-95ee-a3c2bd858ada.png)
and even after log in/log out error messages

Observation 3:  ff version 46 is working

**Comment by mpdl-knoth** [comment]
Fixed please test it again

**Comment by hofmannc** [comment]
retest on ff 58.0.1 ok
