### ISSUE TITLE
Download CDC -> Website nicht erreichbar

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#239]
Testserver: http://app-keeper.mpdl.mpg.de
Browser: chrome
test date: 31.01.2018       

Actions: select library -> "Cared Data Certificate" -> "Download" ->

Observation: 
![grafik](https://user-images.githubusercontent.com/14921701/35614844-b1be15ce-0670-11e8-9cf4-1db68a471633.png)

working for ff

**Comment by vmakarenko** [comment]
related to #238

**Comment by vmakarenko** [comment]
should be fine after closing #238

**Comment by kleinfe** [comment]
This problem still occurs

**Comment by kleinfe** [comment]
Duplicate to #244
