### ISSUE TITLE
Project catalog order correct?

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#240]
Testserver: http://app-keeper.mpdl.mpg.de
Browser: chrome
test date: 31.01.2018

Action: 
"open project catalog" -> 
![grafik](https://user-images.githubusercontent.com/14921701/35615073-65aea954-0671-11e8-8a7c-c68e5c47e9e0.png)

is this order correct?

**Comment by vmakarenko** [comment]
The ordering rule is: **last changed first**. 
The presented order is correct.
