### ISSUE TITLE
E-Mail after CDC creation not sent out

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#241]
Testserver: http://app-keeper.mpdl.mpg.de
Browser: ff and chrome
test date: 31.01.2018    

Observation: right after the creation of the certicicate, there is no e-mail sent out to the creator.

Expected result: Creator recevies an e-mail "you have sucessfully crested ..."

**Comment by kleinfe** [comment]
seems like no emails are sent

**Comment by vmakarenko** [comment]
fixed, related #245

**Comment by kleinfe** [comment]
fixed

**Comment by kleinfe** [comment]
i just tested this issue with cdc generation and not working again

**Comment by vmakarenko** [comment]
Retested, it works fine. Cannot reproduce. Did you check a spam  folder?
