### ISSUE TITLE
Save pages like "about Keeper Service"?

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#242]
Testserver: https://keeper.mpdl.mpg.de/f/d17ecbb967/
Browser: ff
test date: 31.01.2018

Actions: 1. "About the Keeper Service"  	2. -> ""Speichern unter..."  	3. select [valid library)

Observation: "Save"page is not possible
Expected result: Wasn't there a "Save " option? at least we have a test case saying so.

**Comment by kleinfe** [comment]
There is a 'download' button. As the behaviour is the same on live server I assume this is the right behaviour 
![grafik](https://user-images.githubusercontent.com/1484773/35673750-bf846438-0742-11e8-870c-504c2d2d3e2c.png)
