### ISSUE TITLE
Open any PDF -> "Interner Fehler"

### ISSUE THREAD

**Issue by aapetrova** [MPDL/KEEPER#244]
Test server: http://app-keeper.mpdl.mpg.de
Browser: Chrome 63, Firefox 46
Test date: 01.02.2018

Actions: Select any library -> Cared-Data-Certificate-HowTo.pdf -> Interner Fehler,
the same error occurs with uploaded PDF files

![error_pdf_open](https://user-images.githubusercontent.com/19643761/35671404-9a3ae7b2-073b-11e8-81e1-9053c64e7864.png)

Downloading the file works fine.

**Comment by vmakarenko** [comment]
Fixed, but not stable, pls test further

**Comment by kleinfe** [comment]
Conversion fails for all documents i tested

**Comment by kleinfe** [comment]
error for xslt preview
![grafik](https://user-images.githubusercontent.com/1484773/35689397-ae71f3c8-0773-11e8-8e6d-2b8de4d3c43d.png)

**Comment by vmakarenko** [comment]
memcached in cluster problem. background server lose connection to seafile server due to corrupted session in clustered memcached. Solution: use memcached in single mode. Check https://forum.seafile.com/t/memcached-problems/4892/42 for details

**Comment by kleinfe** [comment]
problem identified and will be fixed with upgrade 6.2
