### ISSUE TITLE
No Cared Data Certificate is generated

### ISSUE THREAD

**Issue by aapetrova** [MPDL/KEEPER#245]
Test server: http://app-keeper.mpdl.mpg.de
Browser: Chrome 63, Firefox 46
Test date: 01.02.2018

Actions: Create new library -> Upload file -> Edit archive metadata -> No certificate generated,
Create new library -> Edit archive metadata -> Upload file -> No certificate generated

The project shows up as certified in the project catalogue ("An approach to testing the presence of certificates") and the data in archive-metadata.md was similar to changes done on 31.01, when this problem did not occur.

**Comment by vmakarenko** [comment]
fixed, related #241

**Comment by kleinfe** [comment]
fixed
