### ISSUE TITLE
Moving files deletes associated comments?

### ISSUE THREAD

**Issue by ioverka** [MPDL/KEEPER#249]
Testserver: keeper
Browser: ff
Server Version: 6.1.3
User: standard user

Before moving the file from one sub directory to another:

![keeper1](https://user-images.githubusercontent.com/8920469/36117217-186f9abe-1039-11e8-82fb-71af7cb43e99.png)

... and after:

![image](https://user-images.githubusercontent.com/8920469/36116593-13eb0ca0-1037-11e8-820a-d8db23a00dc7.png)

Is this done on purpose? If yes, a notification for the user would be appreciated...

**Comment by ioverka** [comment]
Oh, the comments can be restored by moving the file back to its origin folder.

**Comment by ioverka** [comment]
Moving files also creates issues for the notifications, e.g. if somebody follows the link an error "file not found" is displayed.

**Comment by vmakarenko** [comment]
Reproduced for seafile pro 6.2.13

**Comment by freeplant** [comment]
Hi, it will be fixed in version 6.3 pro. In version 6.3, we added a way to keep sharing links, file comments, file labels after file moving or renaming.

**Comment by kleinfe** [comment]
Upgrade to Version 6.3.1. is done and will be released in november
