### ISSUE TITLE
Add fsck check to monitoring

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#25]

**Comment by vmakarenko** [comment]
seaf-fsck.sh (seafile Object Storage integrity check) takes place once a week regarding to `__DAY_TO_CHECK_INTEGRITY__` param as a apart of the keeper backup procedure. It breaks backup in case of RC != 0 (TBD). 
Suggested solution: call icigna WEB API directly from backup script, check https://www.icinga.com/category/technical/api/#actions

**Comment by vmakarenko** [comment]
Solution is simple:
icigna script 
RESULT=$(grep -rn corrupted /var/log/keeper/keeper_backup.*)
if [ -n "$RESULT" ]; then
    echo "ERROR, corrupted blocks: ${RESULT}"
fi

**Comment by kleinfe** [comment]
discuss with @mpdl-knoth how we get notification.

**Comment by kleinfe** [comment]
is there any update?

**Comment by vmakarenko** [comment]
That will be covered with the icinga built-in log checker

**Comment by kleinfe** [comment]
@mpdl-knoth pls.check

**Comment by mpdl-knoth** [comment]
Is imtegrated.
