### ISSUE TITLE
File Vorschau stabilisieren

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#252]
Die Dokumenten Vorschau kann wiederholt nicht angezeigt werden (Internal Server Error)

**Comment by vmakarenko** [comment]
The crash of the doc preview system is not regular. Debug of the problems is limited. Possible actions:  
* use  pdf.js for pdf preview (USE_PDFJS = True in seahub_settings.py). More stable and has better  performance  
* check logs, ask seafile for debugging options
