### ISSUE TITLE
One digit password possible

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#257]
Testserver: qa keeper
Browser: ff 59.0.1 (64-Bit)
Version: Seafile 6.1.3 ohne Datum 180326

Actions: 
LOg In user -> "Passwort vergessen " -> select one digit password ->

Observation: Password reset sucessful

**Comment by kleinfe** [comment]
@vmakarenko can you please test if this is because of our settings on qa keeper. If not please report to seafile

**Comment by vmakarenko** [comment]
Set Password->strong password enabled in /sys/settings/. 
strong password: enabled
force password change: enabled 
password minimum length: 6
password strength level: 3
enable two factor authentication: disabled

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: ff 59.0.1 (64-Bit)
Version: Seafile 6.2.13 ohne Datum 180711

Result: ok
