### ISSUE TITLE
Download button of "CDC How to" not completely displayed

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#258]
Testserver: qa keeper
Browser: ff 59.0.1 (64-Bit)
Version: Seafile 6.1.3 ohne Datum 180326
Actions:
open library -> "Cared-Data-Certificate-How-To.pdf" -> "link" -> Download button ragt aus dem Feld heraus (Ticket)
![180326_screenshot](https://user-images.githubusercontent.com/14921701/37909774-1993b940-310c-11e8-8103-834fa41edf81.JPG)

**Comment by kleinfe** [comment]
Just tested, seems to be fixed now
