### ISSUE TITLE
Add virus check to monitoring

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#26]

**Comment by vmakarenko** [comment]
Tip: check `get_virus_record`  https://github.com/haiwen/seahub/blob/master/seahub/utils/__init__.py#L668

**Comment by vmakarenko** [comment]
Solution: 
Directly check seahub_db, TABLE: 
```
SELECT * FROM `VirusFile` WHERE `has_handle`=0
```

**Comment by kleinfe** [comment]
discuss with @mpdl-knoth how to integrate to icinga.

**Comment by kleinfe** [comment]
is there any update?

**Comment by kleinfe** [comment]
@mpdl-knoth pls.check

**Comment by mpdl-knoth** [comment]
This check is also in Icinga now. But this script worked in the first time, after recheck it returned a Traceback

Traceback (most recent call last):
  File "/opt/seafile/scripts/monitoring/viruses_status.py", line 27, in <module>
    db = get_db('seahub-db')
  File "/opt/seafile/scripts/monitoring/viruses_status.py", line 19, in get_db
    charset='utf8')
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2005, "Unknown MySQL server host '__DB_HOST__' (0)")

**Comment by kleinfe** [comment]
did not work in my test. Only the owner of the affected library got an email. No monitoring email was sent.

**Comment by vmakarenko** [comment]
Script works fine on prod, please install check for icinga on it (at the moment I found only for lta05)

**Comment by vmakarenko** [comment]
check has been fixed https://github.com/MPDL/KEEPER/commit/ca223a5b2066cbe98f1b9abce956bab9dc51652a
