### ISSUE TITLE
Implement restart agent for keeper document preview service

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#261]
Keeper document preview service fails unpredictable. 
icinga2 should check the status of the service and try to restart it if it is failed.
Implement firstly on QA.

**Comment by vmakarenko** [comment]
keeper-service status-backround is updated with office_converter check. If the check fails, the RC of the script will be set to 1

**Comment by mpdl-knoth** [comment]
Is not possible at the moment with special modification.
Last test return [seahub] is not runnig.
I needed 5 times to start seahub with user seafile.
The other 4 times I got 
Error:Seahub failed to start.

**Comment by kleinfe** [comment]
@vmakarenko pls. check this issue and close if done
