### ISSUE TITLE
Groups use name instead of ID to ensure uniqueness when created

### ISSUE THREAD

**Issue by jknaus** [MPDL/KEEPER#262]
When creating a new group, Seafile checks if the group already exists by checking its name. 
This has a side effect: 

When somebody else in Keeper has already created a group with the same name, the user gets an error message saying the group already exists, although he cannot see the group itself in the sidebar (if he is not a member). A malicious user could now create libraries with probable group names for his organization and that way "block" these for anybody else.

It would be better if Seafile would check for the group id only instead, i.e. the same behaviour as it does for libraries.

**Comment by kleinfe** [comment]
Thanks for reporting this issue, we will forward it to seafile

**Comment by freeplant** [comment]
Hi @kleinfe, if you turn on cloud mode, users can create groups with the same name. The default mode assumes that it is used in a single organization, and a group name should be unique in that organization.

**Comment by kleinfe** [comment]
@freeplant thanks for the info!
@vmakarenko pls. check our settings

**Comment by kleinfe** [comment]
To be discussed
