### ISSUE TITLE
Improve Projectcatalog

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#266]
add filter functionality:
Show projects
- with metadata
- with certificate
- all

and change title of the page. 
Draft is attached:

![20180614_104020](https://user-images.githubusercontent.com/1484773/41401333-da1ccdd6-6fbf-11e8-8392-01d999bc90a9.jpg)

**Comment by vmakarenko** [comment]
Done. beta 1

**Comment by kleinfe** [comment]
Done
