### ISSUE TITLE
CDC HowTo: Link not working

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#271]
Testserver: qa keeper
Browser: ff 59.0.1 (64-Bit)
Version: Seafile 6.2.13 ohne Datum 180711

Actions: log in -> select library ->  "cared data certificate Howto" -> 
![grafik](https://user-images.githubusercontent.com/14921701/42569817-1e892804-8512-11e8-9910-007d1f2be0eb.png)
 
Observation: Link not clickable

**Comment by vmakarenko** [comment]
This is probably an issue of pdf.js usage

**Comment by kleinfe** [comment]
Unfortunaltly we can not influence it
