### ISSUE TITLE
Certificate still available in project catalog after CDC PDF deletion

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#272]
Testserver: qa keeper
Browser: ff 59.0.1 (64-Bit)
Version: Seafile 6.2.13 ohne Datum 180711

Actions: create library -> fill out metadata form correctly -> create CDC
-> open project catalog -> library available for all facets (with metadata/with certificate/all)

-> open library again -> delete certificate

Observation:

-> open project catalog -> library still available in facet "with certificate" -> blue lable still displayed although no certificate in library available

**Comment by kleinfe** [comment]
@hofmannc pls. retest and close if fixed
