### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#273]
Testserver: qa keeper
Browser: ff 59.0.1 (64-Bit)
Version: Seafile 6.2.13 ohne Datum 180712

Actions:
start page -> 
1. link broken and hardly readable
![grafik](https://user-images.githubusercontent.com/14921701/42624268-4838f734-85c5-11e8-9db8-62bc4e876be1.png)

2. logo not displayed -> this is applicable for all pages
![grafik](https://user-images.githubusercontent.com/14921701/42624344-79392d54-85c5-11e8-89a8-9a888a14c0b5.png)

3. 
![grafik](https://user-images.githubusercontent.com/14921701/42627634-dcb3c9b8-85cd-11e8-9948-481b29d16614.png)

4. footer is not entirely displayed within screen
![grafik](https://user-images.githubusercontent.com/14921701/42627869-981adeb2-85ce-11e8-9f03-933e1ea34c14.png)

5. 
![grafik](https://user-images.githubusercontent.com/14921701/42627945-d45a5b14-85ce-11e8-9e59-8b1ca8dccc33.png)

**Comment by vmakarenko** [comment]
Deployment problem, fixed

**Comment by kleinfe** [comment]
Fixed
