### ISSUE TITLE
Documents uploaded earlier cannot be displayed/Document upload not working

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#274]
Testserver: qa keeper
Browser: ff 59.0.1 (64-Bit)
Version: Seafile 6.2.13 ohne Datum 180711

Actions: 
all documents the user uploaded before the latest version cannot be displayed "Dokumentenkonvertierung fehlgeschlagen" or "Das Bild konnte nicht geladen werden"

If items are uploaded in this version, the data preview works fine

UPDATE: in today's version, no file upload possible and the uploaded files cannot be displayed either

**Comment by vmakarenko** [comment]
Probably a caching problem. Please test again.

**Comment by vmakarenko** [comment]
Deployment problem, fixed
