### ISSUE TITLE
Error by upload into shared pwd-protected library

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#275]
Reported by Andreas Vogler

**Comment by vmakarenko** [comment]
![error](https://user-images.githubusercontent.com/4024310/42763120-6957bf72-8912-11e8-834b-e1bca24997fe.jpg)

**Comment by vmakarenko** [comment]
Checked @ PROD and new QA (1.4)
Works fine, to be checked after 1.4 release

**Comment by kleinfe** [comment]
problem did not occure again, therefore closed
