### ISSUE TITLE
Expand group drop-down list

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#278]
Communicated by Margit:
Group drop-down list ![flhmnopmjngnpgmo.png](https://images.zenhubusercontent.com/56a60a326caf56c9d38be108/f8897a7c-aedf-4ab3-b870-02540079cc1d) is too narrow for MPG group names which are tends to be long and braked down in the list. 
Solution: adjust css props of the list (ticket @seafile?)

**Comment by kleinfe** [comment]
ToDo: Discuss with seafile

**Comment by kleinfe** [comment]
minor
