### ISSUE TITLE
CDC - Adjust Email Text

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#28]
From: KEEPER Service keeper@mpdl.mpg.de
Subject: Cared Data Certificate for project "<Title>" (nicht Bibliothekenname) 

Dear <Emailadresse Owner user>,
you have successfully registered your research project <Title> by 
<Author List> (Formatierung wie auf Zertifikat) 
for long term compliant archiving according to the rules for data storage of the Max Planck Society. The data are kept in the KEEPER system under the library name 
<library name> (mit Link zur Library in Seahub). 
Maintainer of the Record is 
<Emailadresse Owner user>. 
Please make sure you use KEEPER in accordance to the KEEPER Terms of Service and the KEEPER Cared Data Commitment. A Cared Data Certificate was automatically added to your project in KEEPER: 
Cared Data Certificate no. <certificate number> (Link direkt auf das certificate-PDF) 
With best wishes for great progress and break through research results

Your 
KEEPER Service Team 
at the Max Planck Digital Library
## 

KEEPER Support: keeper@mpdl.mpg.de
KEEPER Service Site: https://keeper.mpdl.mpg.de/ 
a service of the 
Max Planck Digital Library (MPDL), Amalienstr. 33, D-80799 München, Germany, www.mpdl.mpg.de, Hotline +49 (0) 89 38602-243 (Montag bis Freitag 7:00-19:00)
Max-Planck-Gesellschaft zur Förderung der Wissenschaften e.V.

**Comment by vmakarenko** [comment]
Probably, email text should be separate for CDC creation and update, see #30

**Comment by vmakarenko** [comment]
No email on UPDATE for start implementation

**Comment by kleinfe** [comment]
checked
