### ISSUE TITLE
Change user invitation workflow

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#281]
If a user is invited to keeper he can register himself at the keeper homepage.
The workflow after that should be the same as for all users:
- With MPG Email he will be activated automatically and gets full user rights (not guest)
- All other email adresses: an email is sent to keeper support and the user has to be activated by hand

**Comment by kleinfe** [comment]
tested

**Comment by hofmannc** [comment]
Testserver: dev keeper
Browser: ff 59.0.1 (64-Bit)
Version: Seafile 6.3.6 ohne Datum 181017
result: nok for non-MPG e-mails

-> invited c@herina and breddin@mpdl.mpg.de on 17.10.18 (listed in admin section) -> Iris received an e-mail, I did not so far (also checked spam folder).

**Comment by vmakarenko** [comment]
cannot reproduce

**Comment by vmakarenko** [comment]
Wrong type of account for invitations at /sys/invitationadmin/ interface:
<code>Guest</code> - > should be <code>Default</code> 
 This is only a presentation problem, type of created account is <code>Default</code>

**Comment by vmakarenko** [comment]
New specs for 1.6: 
- only MPG users can invite other users
- invited users should be immediately activated

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: firefox
Quantum
Version: Seafile 6.3.6 ohne Datum 190214
result: ok
mails sent out correctly - mpg user has invitation grants, non-mpg user has no invitation grants

**Comment by vmakarenko** [comment]
Implement pytest units for integration tests
