### ISSUE TITLE
Integrate LabCam info on startpage

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#283]
according to:
![lbcam keeper int](https://user-images.githubusercontent.com/1484773/45997221-22254100-c09f-11e8-8b34-45e8009ebdd6.jpg)

Image:
https://keeper.mpdl.mpg.de/f/af2c8f23cc3742f788f1/

**Comment by kleinfe** [comment]
The text should link to: https://play.google.com/store/apps/details?id=de.mpg.mpdl.labcam&hl=de

**Comment by hofmannc** [comment]
Testserver: dev keeper
Browser: ff 59.0.1 (64-Bit)
Version: Seafile 6.3.6 ohne Datum 181011
result: ok

**Comment by kleinfe** [comment]
tested
