### ISSUE TITLE
Provide an overview of all emails sent by Keeper

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#291]
Pls. create a folder in the Keeper project which contains all email texts of keeper (invitation, welcome, notification, share ...). And also, if exists, the email template where the text is placed.

**Comment by kleinfe** [comment]
@yli18 is there a update

**Comment by yli18** [comment]
I created a folder in the Keeper project.
https://keeper.mpdl.mpg.de/d/03ada5845858422aba57/

Email texts are extracted to "README.md" file. Templates are also added to this folder.

**Comment by kleinfe** [comment]
done
