### ISSUE TITLE
md form disappears after deleting other files

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#295]
Testserver: qa keeper
Browser: chrome Version 70.0.3538.77 (Offizieller Build) (64-Bit)
Version: Seafile 6.3.6 ohne Datum 181112

Actions: create library -> fill out md form correctly  -> upload 2 files -> CDC is available in library -> select the two uploaded files -> "delete" -> "trash"-view -> "Clean" -> "all" -> "submit" -> message "one object and one more file deleted" -> go back to library view

Observations: md form is not available anymore, although not actively deleted

This issue is not reproducible

**Comment by kleinfe** [comment]
can not reproduce
