### ISSUE TITLE
Check Kibana@mpdl for KEEPER

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#297]
KEEPER dashboard: http://kibana.mpdl.mpg.de/app/kibana#/dashboard/477b8780-a9a7-11e7-8c9d-794abc343072
- check syslog generation app nodes -> syslog server
- check elastic indexes generation syslog -> elastic: logstash, filebeat
- check Kibana visualizations

**Comment by kleinfe** [comment]
i think this is done
