### ISSUE TITLE
Switch on Share Link Feature

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#301]
* `can_send_share_link_mail: True`, seahub_settings.py, ENABLED_ROLE_PERMISSIONS, see `seahub/seahub/role_permissions/settings.py` for details

* new search feature in huge pdfs/docs: Put in `seafevents.conf`
```
[INDEX FILES]
...
highlight = fvh
...
```
  see https://manual.seafile.com/changelog/changelog-for-seafile-professional-server.html

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: firefox
Quantum
Version: Seafile 6.3.6 ohne Datum 190214
result: ok, "share link" is correctly sent to user, user has acces to library by link
