### ISSUE TITLE
Integrate Beta bloxberg connection

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#302]
https://keeper.mpdl.mpg.de/f/93fb448ec74a4fd6ac25/?dl=1

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: firefox
Quantum
Version: Seafile 6.3.6 ohne Datum 190214
result: nok see #324

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: firefox
Quantum
Version: Seafile 6.3.6 ohne Datum 190219
result: ok

**Comment by kleinfe** [comment]
tested
