### ISSUE TITLE
Wrong Timestamp in bloxberg lookup for certified keeper files

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#310]
Bug: 
1. request bloxberg cert for a file with the bloxberg button via keeper WEB-interface
1. lookup the cert via https://bloxberg.org/cert/verify for the file

![Screenshot_20190117_152850.png](https://images.zenhubusercontent.com/56a60a326caf56c9d38be108/65847a99-c583-45bd-8ac4-bf482f21e9df)

**Comment by yli18** [comment]
fixed timestamp and author 
already merged into master 
724723011b327cdb8597fb89e37db1ca3d622124

**Comment by hofmannc** [comment]
not tested

**Comment by vmakarenko** [comment]
Bloxberg explorer is designed to show generic raw data saved in transactions, that is why the Keeper timestamp is shown in the raw representation, i.e. in float number.
