### ISSUE TITLE
Wrong location for some seafile log files (/tmp)

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#312]
Logs: 
```
seahub.log
seahub_django_request.log
```
should be written exclusively into `SEAHUB_LOG_DIR`.
PS: Pls check `seahub.sh` script, `function prepare_seahub_log_dir()`

**Comment by iosifpeterfi** [comment]
Fixed under: https://github.com/MPDL/KEEPER/commit/f09a1921434caaf08abbf2cc6a5a03ab86421dcb and https://github.com/MPDL/KEEPER/commit/f6aadf26489611f461b2a84bc32dd0d8398a5138
