### ISSUE TITLE
Improve virus scanning  on the background server

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#313]
seafile virus scanning with clamav have flaws: 
* scan can run into an infinity loop by unrecognized exceptions due to unsafe exception handling 
* clamav process consumes too many resources on the background server and not really fast

**Comment by iosifpeterfi** [comment]
First topic was handled under:
https://github.com/MPDL/KEEPER/issues/316

**Comment by iosifpeterfi** [comment]
Second topic handled under:
https://github.com/MPDL/KEEPER/commit/4fcb9d2b6f1874d2acf956643748c0b8c25d8722 and https://github.com/MPDL/KEEPER/commit/897bbc1a2b655ef1346ebc85dac5b0d300fc598d
