### ISSUE TITLE
bloxberg popup pimp

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#317]
![grafik.png](https://images.zenhubusercontent.com/5694c167638e718c995ffe4e/732416fb-f56c-453e-b74a-277271f9119c)

**Comment by kleinfe** [comment]
The webaddress should be linked

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: firefox
Quantum
Version: Seafile 6.3.6 ohne Datum 190214
result: ok, linked now
