### ISSUE TITLE
mysql privileges deescalation for debian-sys-maint user

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#325]
Errors in Cron Daemon logs on app-bg-keeper and app01-keeper
```
/etc/cron.daily/logrotate:
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'debian-sys-maint'@'localhost' (using password: YES)'
error: error running shared postrotate script for '/var/log/mysql/mysql.log /var/log/mysql/mysql-slow.log /var/log/mysql/mariadb-slow.log /var/log/mysql/error.log '
run-parts: /etc/cron.daily/logrotate exited with return code 1
```
After manual setting of correct privileges for the user, some other unknown process deescalates it back.

**Comment by iosifpeterfi** [comment]
Waiting for event to occur once more to troubleshoot.
Unable to replicate.

**Comment by iosifpeterfi** [comment]
The root cause was a mariadb update.
Renamed the debian.cnf file and reconfigured the mariadb package, which recreated the debian.cnf. This should withstand a future mariadb update.
