### ISSUE TITLE
Fix bug in share email

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#336]
When using the link from the share email, i get the information "permission denied".
When using the link in my notifications the link is working

**Comment by vmakarenko** [comment]
Cannot reproduce

**Comment by vmakarenko** [comment]
Can reproduce: 
Direct email message sent to user has a link to the library of the shared (sub-)directory and not the link of the shared (sub-)directory itself. User message inder the messages bell has a correct link.

**Comment by vmakarenko** [comment]
fixed in seafile pro 6.3.13, keeper will be migrated to the version in 1.8

**Comment by vmakarenko** [comment]
Fixed by seafile
