### ISSUE TITLE
Minimize email sending after account creation

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#337]
An email should only be sent if an admin has to take a action. This is necessary for the after the following conditions:

1. The user has no mpg email address
2. The user was not invited by another user with a mpg user address

**Comment by kleinfe** [comment]
not sure about the workflow here, tbd at next keeper jour fix

**Comment by vmakarenko** [comment]
Schon implementiert wie beschrieben


---------------------------
Vladislav Makarenko
System Engineer | Digital Labs
Max Planck Digital Library | www.mpdl.mpg.de
Amalienstr. 33 | 80799 Munich | Germany
+49 89 38602-223 | makarenko@mpdl.mpg.de


________________________________
