### ISSUE TITLE
CDC - Email

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#34]
Pls. remove Affiliation of Author.
Despite the specification I experienced during testing that it unnecessarily blows up the email text and makes it harder to read.

e.g.: 
"Dear Friederike Kleinfercher, 
you have successfully registered your research project "F-O-G ring formation in glycopeptide antibiotic biosynthesis is catalysed by OxyE" by Peschke, Madeleine; Department of Biomolecular Mechanisms, Max Planck Institute for Medical Research, Max Planck Society; Brieke, Clara; Department of Biomolecular Mechanisms, Max Planck Institute for Medical Research, Max Planck Society; Cryle, Max J.; Department of Biomolecular Mechanisms, Max Planck Institute for Medical Research, Max Planck Society; for long term compliant archiving according to the rules for data storage of the Max Planck Society. The data are kept in the KEEPER system under the library name Test 14.11.2016 -2. 
"

**Comment by vmakarenko** [comment]
- Affiliations will be cut
- Authors will be separated with "; "

**Comment by kleinfe** [comment]
checked
