### ISSUE TITLE
Install Keeper proxy email server to consolidate Keeper email messaging

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#344]
At the moment Seafile email messaging is not consolidated: it is scattered between functionalities and does not have reliable logging/exception handling. The proxy server should facilitate the control over the Keeper email messaging. Possible workflow:
 * Keeper sends emails to the proxy server 
 * messages are redirected to external email server (e.g. email.gwdg.de)
 * if messages cannot be delivered to the external server, the proxy tries to resend it

**Comment by vmakarenko** [comment]
Installed on PROD

**Comment by kleinfe** [comment]
Pls close if this issue is done
