### ISSUE TITLE
Implement monitoring for Keeper Office Online Service

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#345]
* icinga checks for `*.oos.mpdl.mpg.de` services
* Office Online Service usage dashboard on Keeper Kibana: 
  * number of opened/edited files 
  * number of OOS users
  * number of collaborations: number of  files edited by more than one user

**Comment by kleinfe** [comment]
We should integrate the statistics to get an idea which servers we need for the OOS cluster, which is scheduled for mid/end 2019

**Comment by iosifpeterfi** [comment]
Configuration changes have been created internally and the monitoring is running. It will be documented further on the next release.
