### ISSUE TITLE
Problem "File is locked by another users on the server" reappeared

### ISSUE THREAD

**Issue by ioverka** [MPDL/KEEPER#354]
Version: Seafile Client 6.2.11
BS: Windows 7

![image](https://user-images.githubusercontent.com/8920469/57864015-6fefe480-77fb-11e9-9cd8-f52977ef3ce4.png)

**Comment by ioverka** [comment]
**Assumption**: Problem could have been caused by an unintended computer restart.

**Subsequent procedure**:
* select "Neu synchronisieren" for library from Seafile menu
* confirm "Ja"
* oder "mit vorhandenem Ordner synchronisieren"

This resolves the issue, i.e. the orange exclamation mark is replaced by a green cloud. The corresponding snapshot lists a couple of conflict files, see https://keeper.mpdl.mpg.de/repo/history/12cb8b36-8d6c-45bb-8a4f-e9196ad45260/ Modification Details; 2019-05-16 16:56:44)

**Comment by ioverka** [comment]
The snapshot is a bit weird though, e.g.

```
New files

    OA Publishing/Anschreiben_Einrichtungen_OAPublishingOnboarding_Inga.docx
    OA Publishing/Anschreiben_Einrichtungen_OAPublishingOnboarding_final.docx
```

1. The timestamp on "Anschreiben_Einrichtungen_OAPublishingOnboarding_Inga.docx" is: 2019-05-02 
2. The timestamp on "Anschreiben_Einrichtungen_OAPublishingOnboarding_final.docx" is: 2019-04-26

**Comment by MPDLRanger** [comment]
closing, please get in touch with us in case it still appears
