### ISSUE TITLE
DOI assignment for firefox not sucessful

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#358]
Testserver: qa keeper
Browser: firefox quantum 67.0.4 (64-Bit)
Version: Seafile 6.3.12

Actions: create library -> upload file -> fil out md form correctly -> library menue -> "more actions" -> "Assign DOI to current state"

Observation: Notifications: no sucess message coming up

Expected Result: success notification with link is displayed -> working for Chrome and Opera

Update: after several tries, finally able to assign DOI in this ff version - what happened?

**Comment by vmakarenko** [comment]
Tested on Linux FF 67.0.4 (64-bit): works fine

**Comment by hofmannc** [comment]
enhancement proposal: install notification if DOI assigment has not been sucessful

**Comment by vmakarenko** [comment]
DOI_TIMEOUT has been added to DOXY requets implementetion
