### ISSUE TITLE
CDC Problems

### ISSUE THREAD

**Issue by loughin** [MPDL/KEEPER#36]
Hier sind noch ein paar Kleinigkeiten, die mir gerade bei der CDC Fuktion aufgefallen sind. Ich weiss auch nicht, ob sie wirklich unerwünscht sind.

1. Die Beschreibung des Projektes muss nicht mehr als vier Zeilen enthalten. Soll der Nutzer nicht darüber verständigt werden ? Vielleicht sollte der Nutzer bei der Bearbeitung der Datei archive-metada.md daran gehindert werden, mehr als vier Zeilen einzutippen. Bzw. eine Zeile nach // Please enter the description of your research project hinzufügen.

2. Wenn man die optionale Kommentare ändert, musste nicht das Zeugnis geändert werden, weil kein Kommentar in ihm steht. Jedoch habe ich festgestellt, dass sich eine Änderung der Kommentar auf dem feld "Letzte Äanderung" auswirkt. (das selbe gilt im Fall des Jahr-Feldes.)

**Comment by vmakarenko** [comment]
Die Anmerkungen sind sehr schwer für derzeitige Implementierung, i.e. mit markdown. realisierbar.  
Das kann später implementiert werden, wenn metadaten mit einer Eingabemaske ausgefühlt werden.

**Comment by kleinfe** [comment]
1. Der Nutzer kann und soll einen Titel eingeben mit gewünschter länge. Dieser Titel wird auch vollständig gespeichert. Nur die Darstellung im Zertifikat ist wegen der lesbarkeit gekürzt.

**Comment by kleinfe** [comment]
2. Das Metadatum Kommentar wurde entfernt.
