### ISSUE TITLE
Change Help Links

### ISSUE THREAD

**Issue by MPDLRanger** [MPDL/KEEPER#368]
1) change help/Hilfe links to https://mpdl.zendesk.com/hc/en-us/categories/360001234340-Keeper (Login page, Footer Keeper Web)
2) change banner on login page to knowledge base advert w/ link
3) Add "help" button to all Keeper Web pages (please see Zendesk Support, Admin, Widget, Setup: https://mpdl.zendesk.com/agent/admin/widget)

ToDo: create banner

**Comment by vmakarenko** [comment]
Done: 
1. Help Links
3. "help" button to Zendesk KC
