### ISSUE TITLE
Low: archiving should not be possible while library is being archived

### ISSUE THREAD

**Issue by MPDLRanger** [MPDL/KEEPER#374]
while archiving is in process (= has not yet completed), archiving of the same library should not be possible

**Comment by vmakarenko** [comment]
same to QUEUED archiving

**Comment by MPDLRanger** [comment]
please add non-transparent background. Otherwise it works. Thanks!

Currently:
![Unbenannt2](https://user-images.githubusercontent.com/50910440/72148555-70984500-33a1-11ea-82f9-41017d297ab2.JPG)
