### ISSUE TITLE
Wording & Translation for Release 2.0

### ISSUE THREAD

**Issue by MPDLRanger** [MPDL/KEEPER#381]
1)      Sidebar: Landing Page 
ENG: Library Details
DE: Bibliotheksdetails
 
2)      Dropdown: Archive Library
ENG: (no change) Archive Library
DE: Bibliothek archivieren
 
3)      My Libraries Button: Archive 
ENG: (no change) Archive 
DE: Archivieren
 
4)      My Libraries Button: Archive 
ENG: (no change) Archive 
DE: Archivieren
 
5)      Archive Library Popup Window
ENG: 
Headline: (no change) Archive xyz
Body: 
By archiving this library, the current state of everything contained within it will be archived on a dedicated archiving system. For more information, please follow the link: Information on Archiving. This library can be archived 5 more times.
Please replace link with (show the text “Information on Archiving”): https://mpdl.zendesk.com/knowledge/articles/360011432700/en-us?brand_id=360000413560
Button: (no change) Archive
DE:
Headline: Archivierung von xyz
Body:
Durch die Archivierung der Bibliothek wird ein Snapshot der Bilbiothek und deren Inhalt in ein dediziertes Archivierungssystem kopiert. Für mehr Informationen folgen Sie bitte dem nachfolgenden Link: Informationen zur Archivierung.
Diese Biliothek kann noch 5 mal archiviert werden.
Link (same as in eng): https://mpdl.zendesk.com/knowledge/articles/360011432700/en-us?brand_id=360000413560
Button:
Archivieren
 
6)      Notification: Archive for current library is QUEUED
ENG: Archiving has started. 
DE: Archivierung hat begonnen.
 
7)      Notification: Library is already in archiving task queue, status: PROCESSING
ENG: This library is currently being archived. 
DE: Diese Biliothek wird derzeit bereits archiviert.
 
8)      Notification: Archive for xyc is DONE
ENG: Archive for xyc has been successfully created.
DE: Archiv für xyc wurde erfolgreich erstellt. 
 
9)      Notification: Can not archive, the library snapshot is already archived.
ENG: Cannot archive, since the library snapshot has already been archived.
DE: Archivierung nicht möglich, da der Snapshot bereits archiviert wurde.
 
10)    Notification: Can not archive due to quota expired, please contact support.
ENG: Cannot archive, since the maximum number of archives for this library has been reached. Please contact Keeper support.
DE: Archivierung nicht möglich, da die maximal Anzahl der Archive für diese Bibliothek bereits erstellt wurde. Bitte kontaktieren Sie den Keeper Support. 
 
11)    Notification: Can not archive, the library is too big.
ENG: Cannot archive, since the library is too large. 
DE: Archivierung nicht möglich, da die Biliothek zu groß ist.

**Comment by MPDLRanger** [comment]
1.	Archive Library Popup Window

Please replace link ( https://mpdl.zendesk.com/knowledge/articles/360011432700/en-us?brand_id=360000413560) to knowledge base (ENG and DE) with
Link: https://mpdl.zendesk.com/hc/en-us/articles/360011432700-Archiving
DE: replace „Diese Biliothek kann noch 5 mal archiviert werden.“ with 
„Diese Bibliothek kann noch 5 Mal archiviert werden.“

2.	Archiving task is started.
ENG: Archiving has started.
DE: Archivierung hat begonnen.

3.	Archiving is in progress: Extract library from object storage.
ENG: This library is currently being archived.
DE: Diese Biliothek wird derzeit bereits archiviert.

4.	Notification: Archive for xyc is DONE
ENG: Archive for xyc has been successfully created.
DE: Archiv für xyc wurde erfolgreich erstellt.

**Comment by yli18** [comment]
MSG_DB_ERROR = 'Error by DB query.'
MSG_ADD_TASK = 'Cannot add task.'
MSG_WRONG_OWNER = 'Wrong owner of the library.'
MSG_MAX_NUMBER_ARCHIVES_REACHED = 'Max number of archives for library is reached.'
MSG_CANNOT_GET_QUOTA = 'Cannot get archiving quota.'
MSG_CANNOT_CHECK_REPO_SIZE = 'Cannot check library size.'
MSG_CANNOT_CHECK_SNAPSHOT_STATUS = 'Cannot check snapshot archiving status.'
MSG_LIBRARY_TOO_BIG = 'The library is too big to be archived.'
MSG_EXTRACT_REPO = 'Cannot extract library.'
MSG_ADD_MD = 'Cannot attach metadata file to library archive.'
MSG_CREATE_TAR = 'Cannot create tar file for archive.'
MSG_CALC_CHECKSUM = 'Cannot cannot calculate checksum for archive.'
MSG_PUSH_TO_HPSS = 'Cannot push archive to HPSS.'
MSG_ARCHIVED = 'The library is successfully archived.'
MSG_CANNOT_FIND_ARCHIVE = 'Cannot find archive.'
MSG_SNAPSHOT_ALREADY_ARCHIVED = 'The snapshot of the library is already archived.'
MSG_LAST_TASK_FAILED = 'The last archiving task is failed.'
MSG_CANNOT_QUERY_TASK = 'Cannot query archiving task.'
MSG_UNKNOWN_STATUS = 'Unknown status of archiving task.'
MSG_CANNOT_ARCHIVE_NON_CRITICAL = 'Archiving task is failed.'
MSG_CANNOT_ARCHIVE_CRITICAL = 'Archiving task is failed due to system error, Keeper Team is informed and looking for solution.'
MSG_PROCESSING_STATUS = {
'BUILD_TASK': 'Archiving task is started.',
'EXTRACT_REPO': 'Extract library from object storage.',
'ADD_MD': 'Add metadata file to archive.',
'CREATE_TAR': 'Create archive tar from extracted library.',
'PUSH_TO_HPSS': 'Push archive to HPSS.',
}

On 4. Feb 2020, at 13:24, MPDLRanger <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  Archive Library Popup Window

Please replace link ( https://mpdl.zendesk.com/knowledge/articles/360011432700/en-us?brand_id=360000413560) to knowledge base (ENG and DE) with
Link: https://mpdl.zendesk.com/hc/en-us/articles/360011432700-Archiving
DE: replace „Diese Biliothek kann noch 5 mal archiviert werden.“ with
„Diese Bibliothek kann noch 5 Mal archiviert werden.“

  1.  Archiving task is started.
ENG: Archiving has started.
DE: Archivierung hat begonnen.

  2.  Archiving is in progress: Extract library from object storage.
ENG: This library is currently being archived.
DE: Diese Biliothek wird derzeit bereits archiviert.

  3.  Notification: Archive for xyc is DONE
ENG: Archive for xyc has been successfully created.
DE: Archiv für xyc wurde erfolgreich erstellt.

**Comment by MPDLRanger** [comment]
English

MSG_DB_ERROR = 'Error by DB query.' 
MSG_ADD_TASK = 'Cannot add task.' 
MSG_WRONG_OWNER = 'Cannot archive. User is not the owner of the library.' 
MSG_MAX_NUMBER_ARCHIVES_REACHED = 'Maximum number of archives for the library has been reached.' 
MSG_CANNOT_GET_QUOTA = 'Cannot get archiving quota.' 
MSG_CANNOT_CHECK_REPO_SIZE = 'Cannot check library size.' 
MSG_CANNOT_CHECK_SNAPSHOT_STATUS = 'Cannot check archiving status of the snapshot.' 
MSG_LIBRARY_TOO_BIG = 'The library is too big to be archived.' 
MSG_EXTRACT_REPO = 'Cannot extract library.' 
MSG_ADD_MD = 'Cannot attach metadata file to the library archive.' 
MSG_CREATE_TAR = 'Cannot create tar file for the archive.' 
MSG_CALC_CHECKSUM = 'Cannot calculate checksum for the archive.' 
MSG_PUSH_TO_HPSS = 'Cannot push archive to HPSS.' 
MSG_ARCHIVED = 'The library has been successfully archived.' 
MSG_CANNOT_FIND_ARCHIVE = 'Cannot find archive.' 
MSG_SNAPSHOT_ALREADY_ARCHIVED = 'The snapshot of the library has already been archived.' 
MSG_LAST_TASK_FAILED = 'The last archiving task has failed.' 
MSG_CANNOT_QUERY_TASK = 'Cannot query archiving task.' 
MSG_UNKNOWN_STATUS = 'Unknown status of archiving task.' 
MSG_CANNOT_ARCHIVE_NON_CRITICAL = 'Archiving has failed.' 
MSG_CANNOT_ARCHIVE_CRITICAL = 'Archiving task has failed due to a system error. The Keeper team has been informed and is looking for a solution.' 
MSG_PROCESSING_STATUS = { 
'BUILD_TASK': 'Archiving has started.', 
'EXTRACT_REPO': 'Extracting library from object storage.', 
'ADD_MD': 'Adding metadata file to archive.', 
'CREATE_TAR': 'Creating archive tar file from extracted library.', 
'PUSH_TO_HPSS': 'Pushing archive to HPSS.', 
}

**Comment by MPDLRanger** [comment]
German

MSG_DB_ERROR = 'Error by DB query.'
MSG_ADD_TASK = 'Cannot add task.'
MSG_WRONG_OWNER = 'Archivierung nicht möglich. Der Nutzer ist nicht der Eigentümer der Bibliothek.'
MSG_MAX_NUMBER_ARCHIVES_REACHED = 'Die maximal Anzahl der Archive für die Bibliothek wurde erreicht.'
MSG_CANNOT_GET_QUOTA = 'Cannot get archiving quota.'
MSG_CANNOT_CHECK_REPO_SIZE = 'Größe der Bibliothek kann nicht ermittelt werden.'
MSG_CANNOT_CHECK_SNAPSHOT_STATUS = 'Cannot check archiving status of the snapshot.'
MSG_LIBRARY_TOO_BIG = 'Die Bibliothek ist zu groß um archiviert werden zu können'
MSG_EXTRACT_REPO = 'Die Bibliothek kann nicht extrahiert werden.'
MSG_ADD_MD = 'Metadaten können dem Archiv nicht hinzugefügt werden.'
MSG_CREATE_TAR = 'Cannot create tar file for the archive.'
MSG_CALC_CHECKSUM = 'Cannot calculate checksum for the archive.'
MSG_PUSH_TO_HPSS = 'Cannot push archive to HPSS.'
MSG_ARCHIVED = 'Die Bibliothek wurde erfolgreich archiviert.'
MSG_CANNOT_FIND_ARCHIVE = 'Archiv kann nicht gefunden werden'
MSG_SNAPSHOT_ALREADY_ARCHIVED = 'Der Snapshot der Bibliothek wurde bereits archiviert.'
MSG_LAST_TASK_FAILED = 'The last archiving task has failed.'
MSG_CANNOT_QUERY_TASK = 'Cannot query archiving task.'
MSG_UNKNOWN_STATUS = 'Unknown status of archiving task.'
MSG_CANNOT_ARCHIVE_NON_CRITICAL = 'Archivierung ist fehlgeschlagen.'
MSG_CANNOT_ARCHIVE_CRITICAL = 'Archivierung ist bedingt durch einen Systemfehler fehlgeschlagen. Das Keeper Team wurde informiert und sucht bereits nach einer Lösung.'
MSG_PROCESSING_STATUS = {
'BUILD_TASK': 'Archivierung wurde gestartet.',
'EXTRACT_REPO': Extrahiere Bibliothek aus dem Objektspeicher.',
'ADD_MD': 'Metadaten werden dem Archiv hinzugefügt',
'CREATE_TAR': 'Tar-Archiv wird aus der extrahierten Bibliothek erstellt.',
'PUSH_TO_HPSS': 'Archiv wird zu HPSS transferiert.',
}

**Comment by yli18** [comment]
I found another two places which need german translation.

"Cannot archive library if the library has no content."
"Archivierung ist nicht möglich, wenn die Bibliothek keinen Inhalt hat."

"Cannot archive library if archive-metadata.md file does not exist."
"Archivierung ist nicht möglich, wenn die archive-metadata.md Datei nicht existiert."



On 4. Feb 2020, at 17:16, MPDLRanger <notifications@github.com<mailto:notifications@github.com>> wrote:


German

MSG_DB_ERROR = 'Error by DB query.'
MSG_ADD_TASK = 'Cannot add task.'
MSG_WRONG_OWNER = 'Archivierung nicht möglich. Der Nutzer ist nicht der Eigentümer der Bibliothek.'
MSG_MAX_NUMBER_ARCHIVES_REACHED = 'Die maximal Anzahl der Archive für die Bibliothek wurde erreicht.'
MSG_CANNOT_GET_QUOTA = 'Cannot get archiving quota.'
MSG_CANNOT_CHECK_REPO_SIZE = 'Größe der Bibliothek kann nicht ermittelt werden.'
MSG_CANNOT_CHECK_SNAPSHOT_STATUS = 'Cannot check archiving status of the snapshot.'
MSG_LIBRARY_TOO_BIG = 'Die Bibliothek ist zu groß um archiviert werden zu können'
MSG_EXTRACT_REPO = 'Die Bibliothek kann nicht extrahiert werden.'
MSG_ADD_MD = 'Metadaten können dem Archiv nicht hinzugefügt werden.'
MSG_CREATE_TAR = 'Cannot create tar file for the archive.'
MSG_CALC_CHECKSUM = 'Cannot calculate checksum for the archive.'
MSG_PUSH_TO_HPSS = 'Cannot push archive to HPSS.'
MSG_ARCHIVED = 'Die Bibliothek wurde erfolgreich archiviert.'
MSG_CANNOT_FIND_ARCHIVE = 'Archiv kann nicht gefunden werden'
MSG_SNAPSHOT_ALREADY_ARCHIVED = 'Der Snapshot der Bibliothek wurde bereits archiviert.'
MSG_LAST_TASK_FAILED = 'The last archiving task has failed.'
MSG_CANNOT_QUERY_TASK = 'Cannot query archiving task.'
MSG_UNKNOWN_STATUS = 'Unknown status of archiving task.'
MSG_CANNOT_ARCHIVE_NON_CRITICAL = 'Archivierung ist fehlgeschlagen.'
MSG_CANNOT_ARCHIVE_CRITICAL = 'Archivierung ist bedingt durch einen Systemfehler fehlgeschlagen. Das Keeper Team wurde informiert und sucht bereits nach einer Lösung.'
MSG_PROCESSING_STATUS = {
'BUILD_TASK': 'Archivierung wurde gestartet.',
'EXTRACT_REPO': Extrahiere Bibliothek aus dem Objektspeicher.',
'ADD_MD': 'Metadaten werden dem Archiv hinzugefügt',
'CREATE_TAR': 'Tar-Archiv wird aus der extrahierten Bibliothek erstellt.',
'PUSH_TO_HPSS': 'Archiv wird zu HPSS transferiert.',
}

**Comment by MPDLRanger** [comment]
A few more changes:

1) Popup Window Archiving: 

- Link is still the old one (please change DE and ENG to https://mpdl.zendesk.com/hc/en-us/articles/360011432700-Archiving)

- DE -> please change button text to "Archivieren", 

- DE -> change "Durch die Archivierung der Bibliothek wird ein Snapshot der Bilbiothek und deren Inhalt in ein dediziertes Archivierungssystem kopiert." to "Durch die Archivierung der Bibliothek wird die aktuelle Version der ausgewählten Bibliothek (Schnappschuss) und deren Inhalt in ein dediziertes Archivierungssystem kopiert."

2) MSG_LAST_TASK_FAILED = 
DE: 'Archivierung fehlgeschlagen. Bitte versuchen Sie es in ein paar Minuten nochmals'
ENG: 'Archiving has failed. Please try again in a few minutes'

3) MSG_SNAPSHOT_ALREADY_ARCHIVED = 
DE: 'Der Schnappschuss der Bibliothek wurde bereits archiviert.'

4) Trying to archive without metadata file
Current: Cannot archive library if archive-metadata.md file is not filled.
ENG: 'Cannot archive library if archive-metadata.md file is not filled or missing'
DE: 'Die Bibliothek kann nicht archiviert werden, sofern die archive-metadata.md Datei nicht ausgefüllt oder nicht vorhanden ist.'

**Comment by MPDLRanger** [comment]
one more:

Diese Biliothek wird derzeit bereits archiviert.
change to 
Diese Bibliothek wird derzeit bereits archiviert.
