### ISSUE TITLE
Office Online PPT

### ISSUE THREAD

**Issue by MPDLRanger** [MPDL/KEEPER#387]
Inserting a picture into PPT does not work at all (no action after pressing the button)

**Comment by MPDLRanger** [comment]
Update: this seems to be Chrome only. Firefox works.

**Comment by vmakarenko** [comment]
I can reproduce, Chrome Version 80.0.3987.132 (Official Build) (64-bit), Ubuntu

**Comment by MPDLRanger** [comment]
![image](https://user-images.githubusercontent.com/50910440/75884529-499c4380-5e25-11ea-90f6-42cad47bdee3.png)

Error in Chrome

**Comment by vmakarenko** [comment]
same to Excel
related: https://stackoverflow.com/questions/59028272/file-chooser-dialog-can-only-be-shown-with-a-user-activation-issue

**Comment by vmakarenko** [comment]
To be tested in MS Edge

**Comment by vmakarenko** [comment]
Same problem on brave 
Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit) on Ubuntu 19.04

**Comment by MPDLRanger** [comment]
adressed to Microsoft: will probably not be fixed - not a Keeper bug
