### ISSUE TITLE
Certificate Processing Observations

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#400]
Testserver: qa keeper
Browser: firefox 74.0 (64-Bit) Chrome 80.0.3987.149
Version: Seafile 6.3.12

Observation: Creation and update of certificates sometimes with delay or notification "cannot process certiicate for library xy"

1. infomail "Certificate created" sometimes came with up to 40 Minutes delay (with Valentin, Catherina could not reproduce it)
2. Updates of certificates sometimes came with with up to 40 munites delay or several certificates at a time (with Valentin, Catherina could not reproduce it)
3. Action: Delete Certificate -> update archive-metadata.md -> observation: Yesterday and this morning there was no new certificate created, but later this morning it worked out as expected (Catherina observed this, Valentin could not reproduce it)
4. Action: Make invalid entry in archive-metadata.md -> no update of certificate (correct) -> make valid entry again -> still no certificate updated (error message: cannot process certificate for library xy) (Catherina could reproduce this several times, later on it worked out fine again, Valentin could not reproduce it)

**Comment by iosifpeterfi** [comment]
Hello,

For 1 and 2, I do not see any email messages delayed on our side, so it might be possible that the email message was delayed on the upstream SMTP server.

For 3 and 4 please provide some additional information:
- Library IDs that were used to generate the certificates
- Time the changes were performed to trigger certificates creation (as precise as you can)

Regards,
Iosif

**Comment by vmakarenko** [comment]
cannot reproduce

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: firefox 74.0 (64-Bit) Chrome 80.0.3987.149
Version: Seafile 6.3.12

Result: ok, could not be redproduced anymore
