### ISSUE TITLE
Delay with switching filters of project view

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#402]
Testserver: qa keeper
Browser: firefox 74.0 (64-Bit) Chrome 80.0.3987.149
Version: Seafile 6.3.12
 
Observation:  Going to "Project Catalog" and Switch between project filters -> "Show projects" : With metadata/with certificate/all  most of the times show a notable delay

**Comment by vmakarenko** [comment]
Fixed.
to QA team: please test  entire catalog view behavior (https://qa-keeper.mpdl.mpg.de/catalog/), facets and  scrolling through catalog pages.

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: firefox 74.0 (64-Bit) Chrome 80.0.3987.149
Version: Seafile 6.3.12
Result: ok, delay not notable anymore, scrolling and switching pages worked out as expected
