### ISSUE TITLE
Library details are not updated

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#403]
Testserver: qa keeper
Browser: firefox 74.0 (64-Bit) Chrome 80.0.3987.149
Version: Seafile 6.3.12

Action: Create library -> make relevant changes in library -> library details

Observation: library not added to library details, landingpages not updated

Expected result: Library added and landing page updated

**Comment by vmakarenko** [comment]
Fixed.
@iosifpeterfi: please add 
```sql
CREATE TRIGGER `update_catalog_archive_status` AFTER UPDATE ON `keeper_archive`
 FOR EACH ROW UPDATE keeper_catalog SET is_archived=1 WHERE repo_id=NEW.repo_id AND is_archived=0 AND NEW.status='DONE' 
```
to the puppet script by `keeper_db` creation.

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: firefox 74.0 (64-Bit) Chrome 80.0.3987.149
Version: Seafile 6.3.12

Result: OK, library details are correctly updated
