### ISSUE TITLE
DOI functionality not available

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#404]
Testserver: qa keeper
Browser: firefox 74.0 (64-Bit) Chrome 80.0.3987.149
Version: Seafile 6.3.12

Actions: Library -> "DOI der aktuellen Version zuweisen" -> 

Observation: E-Mail:

![grafik](https://user-images.githubusercontent.com/14921701/77423019-ca1fe580-6dce-11ea-8a07-d23ff8e7eafe.png)

**Comment by vmakarenko** [comment]
test.doi is not accessible from new QA nodes. Access is requested.

**Comment by vmakarenko** [comment]
Access has been granted.

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: firefox 74.0 (64-Bit) Chrome 80.0.3987.149
Version: Seafile 6.3.12
Result: ok, DOI functionality avalable now.
