### ISSUE TITLE
Share library to user: user did not receive info e-mail (not reproducible)

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#405]
Testserver: qa keeper
Browser: firefox 74.0 (64-Bit) Chrome 80.0.3987.149
Version: Seafile 6.3.12

Actions: Share library by "share" -> "share to user " https://qa-keeper.mpdl.mpg.de/#my-libs/lib/8d5d8e29-6175-4312-8f64-8ee4eddcf46d  -> to helk@mpdl.mpg.de (around 11:20)

Observation: Valentin did not recieive an e-mail, but info was included to notifications and library was actually available for him. Later share actions with other libraries triggered e-mails correctly.

Expected result: e-mail is always sent out within this action

**Comment by vmakarenko** [comment]
This is supposable a correct seafile notification behaviour.  An email notification on sharing will not be sent if the notification icon has been pressed right after sharing action (delay <= 1 min).

**Comment by hofmannc** [comment]
my earlier comment seems not to be added to the ticket, so I write it again:
Testserver: qa keeper
Browser: firefox 74.0 (64-Bit) Chrome 80.0.3987.149
Version: Seafile 6.3.12

Actions: share -> click on notifications right after the share process
share-> click on shared linrary right after sharing process

Observation: We could not  reproduce the behaviour: After each "fast click", we still received an e-mail. In just one exception the user did not receive an e-mail after clicking on notification

--> we assume that the described behaviour (no e-mail if notification clicked earlier) is not the correct behaviour

**Comment by vmakarenko** [comment]
I checked [code](https://github.com/MPDL/KEEPER/blob/master/seafile_keeper_ext/seafile-server-latest/seahub/seahub/notifications/management/commands/send_notices.py#L223). By very fast clicking it is theoretically possible, that DB entry of CommandsLastCheck is above the user notification timepstamp. It can cause the the issue. Anyway, IMO it is highly rare case and does not bring big problems, only email is not sent, notification is provided. BTW I cannot reproduce it.
