### ISSUE TITLE
CDC - When a certificate is deleted it is not generated again

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#41]
In this case a new certificate should be created when the metadata file is updated.

**Comment by vmakarenko** [comment]
TBD

**Comment by kleinfe** [comment]
When I delete a certificate it is regenareted automatically. Please change this, so that a new certificate is only regenerated when the metadata file is updated.

(It is possible that the user intended to delete the certificate and then it is anoying when it is automatically regenrated).

**Comment by vmakarenko** [comment]
TBD

**Comment by kleinfe** [comment]
checked
