### ISSUE TITLE
Office documents can not be opened

### ISSUE THREAD

**Issue by helkv** [MPDL/KEEPER#414]
Testserver: qa keeper
Browser: firefox 78.0b2 (64-Bit) Chrome 83.0.4103.97
Version: Seafile 7.1.3

Actions: open an Office Online document -> an error message is displayed. The content of the document is not displayed.

Observations:
- different Office document types are affected: docx, pptx, xlsx
- different kinds of errors occur:
  - "We couldn't find the file you wanted."
  - "Something went wrong and we couldn't load this content. Refreshing the browser may fix the problem."
  - ...

Expected result: the Office document is displayed and can be edited via Office Online

**Comment by vmakarenko** [comment]
Tested in HO, bad inet connection (packet loss), VPN in MPDL network.

Cannot reproduce in general: all 3 mentioned formats can be opened with OOS. 
However, browser console is full of errors like (pptx): 
```
GET https://win-oos-keeper.mpcdf.mpg.de/p/PptResources/1033/segoeui.woff net::ERR_ABORTED 404
...
POST https://win-oos-keeper.mpcdf.mpg.de/p/ppt/view.svc/jsonAnonymous/GetFullSizePreview 500
```
or (for xlsx, docx):
```
Failed to load resource: the server responded with a status of 404 ()
```

**Comment by helkv** [comment]
Office documents can be displayed and edited via Office Online. Errors cannot be reproduced.

Testserver: qa keeper
Browser: Firefox 78.0b9 (64-Bit), Chrome 83.0.4103.116 (64-Bit)
Version: Seafile 7.1.3
Result: ok
