### ISSUE TITLE
Share/Upload Links can not be send

### ISSUE THREAD

**Issue by helkv** [MPDL/KEEPER#415]
Testserver: qa keeper
Browser: firefox 78.0b2 (64-Bit) Chrome 83.0.4103.97
Version: Seafile 7.1.3

Actions: open a Library -> Send a Share Link (or an Upload Link) to an email-adress -> error occurs: "Failed to send to ... : Internal Server Error"

Expected result: Share/Upload-Links can be send

**Comment by vmakarenko** [comment]
```
seahub.log:
2020-06-08 11:21:34,772 [ERROR] seahub.api2.endpoints.send_share_link_email:111 post {'vlamak868@gmail.com': (454, b'4.7.1 <vlamak868@gmail.com>: Relay access denied')} 
```

**Comment by helkv** [comment]
Testserver: qa keeper
Browser: Firefox 78.0b9 (64-Bit), Chrome 83.0.4103.116 (64-Bit)
Version: Seafile 7.1.3
Result: ok
