### ISSUE TITLE
Problems with pdf-files

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#416]
Testserver: qa keeper
Browser: firefox 77.0.1 (64-Bit) Chrome 83.0.4103.61
Version: Seafile 7.1.3

Actions: open pdf-file, e.g. Cared Data Certificate

Observations: from 16:38 pm on, the pdf-files could not be opened corretly, see screenshot, I tried several files, just one file was displayed one time, the next time it did not work out anymore

![grafik](https://user-images.githubusercontent.com/14921701/83747796-7567d900-a661-11ea-9bd4-42b19820de02.png)

While testing in the morning of June 3rd, there were no problems with pdf display

Expected result: pdf files open correctly

**Comment by vmakarenko** [comment]
I can reproduce the behavior
Ubuntu 20.04
Chrome 83.0.4103.97 (Official Build) (64-bit)
FF 77.0.1 (64-bit)
Bad internet connection from HomeOffice (massive packets loss) and via MPDL VPN
PDFs over 200KB are not displayed, but not always.
Error catched in Chrome DevTools->Console: 
```
net::ERR_CONTENT_LENGTH_MISMATCH 200 
viewer.js:989 Uncaught (in promise) Error: An error occurred while loading the PDF.
    at viewer.js:989
(anonymous) @ viewer.js:989
```
Observation on PROD: same PDFs are always shown.
Seafile logs are clean, no related error messages.

**Comment by vmakarenko** [comment]
fixed: set correct owner for nginx cache dirs. See https://itnext.io/step-over-nginx-buffer-issue-94a498bedb82

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: firefox 77.0.1 (64-Bit) Chrome 83.0.4103.61
Version: Seafile 7.1.3
Result: ok
