### ISSUE TITLE
some jpg-files not completely displayed

### ISSUE THREAD

**Issue by hofmannc** [MPDL/KEEPER#417]
estserver: qa keeper
Browser: firefox 77.0.1 (64-Bit) Chrome 83.0.4103.61
Version: Seafile 7.1.3

Actions: upload jpg file and open it (single upload and batch upload)

Observations: some of the files are not completely displayed while opening it, some files cannot get downloaded ("Quelldatei konnte nicht gelesen werden") others without problems.
![grafik](https://user-images.githubusercontent.com/14921701/83748529-a1378e80-a662-11ea-985e-c8edfb8af4f3.png)

Expected result: all jpg files are completely displayed and downloadable

**Comment by vmakarenko** [comment]
After fixing #416 cannot reproduce anymore.

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: firefox 77.0.1 (64-Bit) Chrome 83.0.4103.61
Version: Seafile 7.1.3
Result: ok
