### ISSUE TITLE
Release 2.1.5

### ISSUE THREAD

**Issue by MPDLRanger** [MPDL/KEEPER#435]
- [x] OnlyOffice
- [x] Security Token OnlyOffice
- [x] Code Adjustments OnlyOffice/Sharing Links
- [x] Custom admin profiles

- [x] Newsletter
- [x] Knowledge Base
- [x] Change Banner OnlyOffice Advert(?)
- [x] Notification in Keeper about Downtime

**Comment by vmakarenko** [comment]
+ `/run/tmp` check/creation by first keeper-service start

**Comment by MPDLRanger** [comment]
released
