### ISSUE TITLE
CDC - What happens when a user deletes the md file?

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#44]
Find solution.

Is it possible to prevent a file from beeing deleted?

**Comment by kleinfe** [comment]
Perhaps he wants to delete the certificate files because he only wants to sync and share?

**Comment by natasab** [comment]
PS. or move them to another location / subfolder

**Comment by vmakarenko** [comment]
User can remove/move all CDC stuff from library, there is no possibility to mark them undeletable. In this case the feature (an catalog as well) does not work.
