### ISSUE TITLE
Catalog - entries should be ordered chronologically

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#52]
The most new one should be the first entry

**Comment by kleinfe** [comment]
date modified

**Comment by vmakarenko** [comment]
Now sorted by last date modified, reversed

**Comment by kleinfe** [comment]
checked

**Comment by kleinfe** [comment]
has changed in new version, seems now to be creation date. please change back to last modification date

**Comment by kleinfe** [comment]
checked
