### ISSUE TITLE
Exchange Keeper Logos

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#54]

**Comment by kleinfe** [comment]
The Keeper logo should be as follows:
Productive: Keeper
QA: Keeper QA
Dev: Keeper Dev

**Comment by kleinfe** [comment]
Done for productive

**Comment by vmakarenko** [comment]
Logos are here: https://keeper.mpdl.mpg.de/#common/lib/a0b4567a-8f72-4680-8a76-6100b6ebbc3e/Keeper%20Software/Logo/Intstance%20Logos
and here: 
https://github.com/MPDL/KEEPER/tree/master/seafile_keeper_ext/seahub-data/custom/{KeeperLogo*}.svg
NOTE: use __LOGO_IMG__ property to define correct logo for intstance

**Comment by kleinfe** [comment]
done
