### ISSUE TITLE
CSS Probleme bei der neusten Version von Seafile (Seafile server 6.0.3)

### ISSUE THREAD

**Issue by loughin** [MPDL/KEEPER#56]
![seafile_server_6 0 3](https://cloud.githubusercontent.com/assets/23240192/20520497/52979ee6-b0a7-11e6-856c-109bf9da2a32.png)

Ich habe die neuste Version von Seafile Server installiert, und die CSS-Datei hinzugefügt

**Comment by kleinfe** [comment]
done
