### ISSUE TITLE
Test keeper deployment procedure

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#57]
See keeper deployment manual: https://keeper.mpdl.mpg.de/f/bb0271c091/

**Comment by kleinfe** [comment]
Bitter plane hierzu einen kleinen Workshop für mich und Ladislas, auf dem du uns den Deployment Prozess erklärst. Wenn möglich noch vor Weihnachten. Danke!

**Comment by vmakarenko** [comment]
Tested for seafile release 6.0.6
