### ISSUE TITLE
CDC - Some style issues

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#6]
![wp_20160809_11_27_12_pro](https://cloud.githubusercontent.com/assets/1484773/17511721/95bfd81c-5e24-11e6-90ac-30fa3188039e.jpg)

**Comment by vmakarenko** [comment]
Fixed on QA, not clear what should be changed up to "bold/kursive" notices.

**Comment by vmakarenko** [comment]
"bold/kursive" issues have been fixed

**Comment by kleinfe** [comment]
Checked!
