### ISSUE TITLE
Check monitoring failure

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#67]
At Dec. 7th the service was not available due to an internal server error. No error message was sent.

**Comment by vmakarenko** [comment]
check availability of `seafile-data` link

**Comment by vmakarenko** [comment]
Possible solutions:
- `check_gpfs_health` nagios plugin
- check whether directory is available: `[ -d "/opt/seafile/seafile-data/storage/blocks" ]` or ` [ -d "/keeper/seafile-fileset/seafile-data/storage/blocks" ]`

**Comment by kleinfe** [comment]
discuss with @mpdl-knoth how we get notification.

**Comment by kleinfe** [comment]
is there any update?

**Comment by vmakarenko** [comment]
Will be implemented with the built-in icinga checker (Benjamin)

**Comment by vmakarenko** [comment]
It is the problem with MPDL icinga itself.
The KEEPER breakdown at 20-01-2017 was not notified as well

**Comment by kleinfe** [comment]
@mpdl-knoth pls. check

**Comment by mpdl-knoth** [comment]
New gpfs check builded and is running in Icinga2.
