### ISSUE TITLE
Add MPCDF comments for monitoring

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#68]
Check with @mpdl-knoth what you discussed at MPCDF (logfiles).

**Comment by vmakarenko** [comment]
1. Logs should be consolidated whenever possible. For the moment all the seafile logs are separated, all seafile service has its own logfile. FYI: only `/opt/seafile/logs` @ PROD has 229 files (21.12.) and size 365Mb 
1. Logs should be moved to the special partition, neither local FS, nor GPFS and be treated regularly up to MPCD/MPDL rules
