### ISSUE TITLE
CDC - Title display

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#7]
https://qa-keeper.mpdl.mpg.de/f/47369f3ef8/

Title should be cut after 2 lines with ...
Currently it is overlapping with author name

**Comment by vmakarenko** [comment]
Fixed: Title, Authors: maximal 2 lines, Description: 4 lines. By overflow text will be cut at the word border and appended with "..."-suffix. Check at QA.

**Comment by kleinfe** [comment]
Checked!
