### ISSUE TITLE
Enhance Keeper Upgrade Strategy

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#76]
Für mich offene Punkte:
- Was tun im Worst case (release funkt nicht). Evtl vor release immer image ziehen, das schnellzurück gespielt werden kann?
- Neustart des Server immer gleich mittesten, da wir hier oft Probleme haben (starten alle Komponenten mit?)

Sollten hierzu ein Meeting planen. @vmakarenko : Noch im Dezember oder erst im januar?

**Comment by vmakarenko** [comment]
>Was tun im Worst case (release funkt nicht). Evtl vor release immer image ziehen, das schnellzurück gespielt werden kann?

**Vlad:** This is easy for minor release upgrades like 6.0.5 -> 6.0.6, i.e. there are not lot of properties and DB changes. What should be backuped before release should be decided for each release separately. It can be:
* `/opt/seafile/conf`directory
* seafile and KEEPER DBs
* ```/opt/seafile/scripts```directory (optionally)
All other KEEPER stuff is already backuped in the `/opt/seafile/seafile-pro-server-x.x.x` directories, the current app-server code is switched with the `ln -s /opt/seafile/seafile-pro-server-CURRENT_VERSION  /opt/seafile/seafile-server-latest` link.
**TODO:** backup KEPPER app-server source code for each release in the GPFS instance fileset


> Neustart des Server immer gleich mittesten, da wir hier oft Probleme haben (starten alle Komponenten mit?)

**Vlad:** [seafile-server.sh](https://github.com/MPDL/KEEPER/blob/master/seafile_keeper_ext/scripts/seafile-server.sh) status shows all PIDs of KEEPER related services and running status of them.

**Comment by vmakarenko** [comment]
Create KEEPER Release Notes template, test it for 1.1 release

**Comment by vmakarenko** [comment]
Related ticket #94
