### ISSUE TITLE
FF 5.0.x upload bug, fixed in 6.0.4

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#79]
Seafile bug, see:
https://github.com/haiwen/seafile/issues/1750
https://github.com/haiwen/seafile/issues/1805
https://forum.seafile.com/t/solved-error-uploading-files-with-firefox-50/1265/12

Workaround: set ENABLE_UPLOAD_FOLDER = False
TODO: For KEEPER migration to 6.0.4: back to True or remove property from seahub_settings.py

**Comment by kleinfe** [comment]
checked
