### ISSUE TITLE
Migration on Seafile Professional edition 6.0.6

### ISSUE THREAD

**Issue by vmakarenko** [MPDL/KEEPER#92]
The full change log:

* Guest invitation: Prevent the same address can be invited multiple times by the same inviter and by multiple inviters
* Guest invitation: Add a regex to prevent certain email addresses be invited
* Office online: support co-authoring
* Admin can set users' department and name when creating users
* Show total number of files and storage in admin info page
* Show total number of devices and recently connected devices in admin info page
* Delete shared libraries information when deleting a user
* Upgrade Django to 1.8.17
* Admin can create group in admin panel
* [fix] Fix quota check: users can't upload a file if the quota will be exceeded after uploading the file
* [fix] Fix quota check when copy file from one library to another
* Add `# -*- coding: utf-8 -*-` to seahub_settings.py, so that admin can use non-ascii characters in the file.
* [fix] Prevent admin from access group's wiki
* [fix] Prevent transfering libraries to guest account
* [fix] Prevent guest account to create share link via API v2
* Add a log when a user can't be find in LDAP during login, so that the system admin can know whether it is caused by password error or the user can't be find

**Comment by kleinfe** [comment]
done
