### ISSUE TITLE
Farben

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#96]
Bitte dieselbe Farbkombination wie auf live Keeper verwenden:
Überschriften: #005c71
Schrift: #57a5b8
Icons: #006f7b
Hoverbox: #f4efde

Es gibt noch an vielen Stellen das Seafile orange. Hier bitte mit search/replace im css alles austauschen.
Einige Beispiele sind im Anhang
![versionen](https://cloud.githubusercontent.com/assets/1484773/21976388/dafd5f50-dbd1-11e6-8df2-410f7be45020.png)
![aktivitaten](https://cloud.githubusercontent.com/assets/1484773/21976392/db02970e-dbd1-11e6-81d8-ee874afabf80.png)
![freigabe](https://cloud.githubusercontent.com/assets/1484773/21976391/db01b0dc-dbd1-11e6-8147-ed03089d9f8f.png)
![lade_balken](https://cloud.githubusercontent.com/assets/1484773/21976389/db004bf2-dbd1-11e6-9b46-5a2828d9b26c.png)
![links](https://cloud.githubusercontent.com/assets/1484773/21976393/db033074-dbd1-11e6-997a-4d420a3ad79e.png)
![pfad](https://cloud.githubusercontent.com/assets/1484773/21976390/db010eca-dbd1-11e6-9a2a-e0e75eea175b.png)
![pfad-file-details](https://cloud.githubusercontent.com/assets/1484773/21976394/db10a268-dbd1-11e6-90ea-dc6c75459f54.png)

**Comment by vmakarenko** [comment]
@loughin pls., commit to the correct directory:
seahub.css and seahub.min.css should be in KEEPER/seafile-server-latest/seahub/media/**css** directory, and not in KEEPER/seafile-server-latest/seahub/media
