### ISSUE TITLE
Suchleiste: Button passt nicht

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#99]
Getestet mit FF auf Windows

![suchleiste](https://cloud.githubusercontent.com/assets/1484773/21976543/a8059742-dbd2-11e6-9e32-acd791713092.png)

**Comment by loughin** [comment]
![bildschirmfoto vom 2017-01-17 11-09-39](https://cloud.githubusercontent.com/assets/23240192/22016186/95d1c6bc-dca5-11e6-8545-4c49bb14c8f9.png)

**Comment by kleinfe** [comment]
checked
